//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.21 at 03:15:08 AM EAT 
//


package xmlparser.kensws.condoc1_v1_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ContainerDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContainerDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Containers" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ContainerNumbers" type="{MDA_Common_Types}ContainerNumbersType"/>
 *                   &lt;element name="ContainerNoOfPacakges" type="{MDA_Common_Types}ContainerNoOfPacakgesType"/>
 *                   &lt;element name="ContainerSize" type="{MDA_Common_Types}ContainerSizeType"/>
 *                   &lt;element name="ContainerSealNo" type="{MDA_Common_Types}ContainerSealNoType"/>
 *                   &lt;element name="ContainerLoadIndicator" type="{MDA_Common_Types}ContainerLoadIndicatorType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContainerDetailsType", propOrder = {
    "containers"
})
public class ContainerDetailsType {

    @XmlElement(name = "Containers", required = true)
    protected List<ContainerDetailsType.Containers> containers;

    /**
     * Gets the value of the containers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the containers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContainers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContainerDetailsType.Containers }
     * 
     * 
     */
    public List<ContainerDetailsType.Containers> getContainers() {
        if (containers == null) {
            containers = new ArrayList<ContainerDetailsType.Containers>();
        }
        return this.containers;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ContainerNumbers" type="{MDA_Common_Types}ContainerNumbersType"/>
     *         &lt;element name="ContainerNoOfPacakges" type="{MDA_Common_Types}ContainerNoOfPacakgesType"/>
     *         &lt;element name="ContainerSize" type="{MDA_Common_Types}ContainerSizeType"/>
     *         &lt;element name="ContainerSealNo" type="{MDA_Common_Types}ContainerSealNoType"/>
     *         &lt;element name="ContainerLoadIndicator" type="{MDA_Common_Types}ContainerLoadIndicatorType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "containerNumbers",
        "containerNoOfPacakges",
        "containerSize",
        "containerSealNo",
        "containerLoadIndicator"
    })
    public static class Containers {

        @XmlElement(name = "ContainerNumbers", required = true)
        protected String containerNumbers;
        @XmlElement(name = "ContainerNoOfPacakges", required = true)
        protected String containerNoOfPacakges;
        @XmlElement(name = "ContainerSize", required = true)
        protected String containerSize;
        @XmlElement(name = "ContainerSealNo", required = true)
        protected String containerSealNo;
        @XmlElement(name = "ContainerLoadIndicator", required = true)
        protected String containerLoadIndicator;

        /**
         * Gets the value of the containerNumbers property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContainerNumbers() {
            return containerNumbers;
        }

        /**
         * Sets the value of the containerNumbers property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContainerNumbers(String value) {
            this.containerNumbers = value;
        }

        /**
         * Gets the value of the containerNoOfPacakges property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContainerNoOfPacakges() {
            return containerNoOfPacakges;
        }

        /**
         * Sets the value of the containerNoOfPacakges property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContainerNoOfPacakges(String value) {
            this.containerNoOfPacakges = value;
        }

        /**
         * Gets the value of the containerSize property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContainerSize() {
            return containerSize;
        }

        /**
         * Sets the value of the containerSize property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContainerSize(String value) {
            this.containerSize = value;
        }

        /**
         * Gets the value of the containerSealNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContainerSealNo() {
            return containerSealNo;
        }

        /**
         * Sets the value of the containerSealNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContainerSealNo(String value) {
            this.containerSealNo = value;
        }

        /**
         * Gets the value of the containerLoadIndicator property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContainerLoadIndicator() {
            return containerLoadIndicator;
        }

        /**
         * Sets the value of the containerLoadIndicator property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContainerLoadIndicator(String value) {
            this.containerLoadIndicator = value;
        }

    }

}
