//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.21 at 03:15:08 AM EAT 
//


package xmlparser.kensws.condoc1_v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DocumentTypeDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DocumentTypeDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DocumentCode" type="{MDA_Common_Types}DocumentCodeType2"/>
 *         &lt;element name="DocumentCodeDesc" type="{MDA_Common_Types}DocumentCodeDescType2" minOccurs="0"/>
 *         &lt;element name="DocumentRef" type="{MDA_Common_Types}DocumentRefType"/>
 *         &lt;element name="ExternalFileName" type="{MDA_Common_Types}ExternalFileName" minOccurs="0"/>
 *         &lt;element name="FileFormat" type="{MDA_Common_Types}FileFormat"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DocumentTypeDetails", propOrder = {
    "documentCode",
    "documentCodeDesc",
    "documentRef",
    "externalFileName",
    "fileFormat"
})
public class DocumentTypeDetails {

    @XmlElement(name = "DocumentCode", required = true)
    protected String documentCode;
    @XmlElement(name = "DocumentCodeDesc")
    protected String documentCodeDesc;
    @XmlElement(name = "DocumentRef", required = true)
    protected String documentRef;
    @XmlElement(name = "ExternalFileName")
    protected String externalFileName;
    @XmlElement(name = "FileFormat", required = true)
    protected String fileFormat;

    /**
     * Gets the value of the documentCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentCode() {
        return documentCode;
    }

    /**
     * Sets the value of the documentCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentCode(String value) {
        this.documentCode = value;
    }

    /**
     * Gets the value of the documentCodeDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentCodeDesc() {
        return documentCodeDesc;
    }

    /**
     * Sets the value of the documentCodeDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentCodeDesc(String value) {
        this.documentCodeDesc = value;
    }

    /**
     * Gets the value of the documentRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentRef() {
        return documentRef;
    }

    /**
     * Sets the value of the documentRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentRef(String value) {
        this.documentRef = value;
    }

    /**
     * Gets the value of the externalFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalFileName() {
        return externalFileName;
    }

    /**
     * Sets the value of the externalFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalFileName(String value) {
        this.externalFileName = value;
    }

    /**
     * Gets the value of the fileFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileFormat() {
        return fileFormat;
    }

    /**
     * Sets the value of the fileFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileFormat(String value) {
        this.fileFormat = value;
    }

}
