//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.21 at 03:15:08 AM EAT 
//


package xmlparser.kensws.condoc1_v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DocumentHeaderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DocumentHeaderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DocumentReference" type="{MDA_Common_Types}DocumentReferenceType"/>
 *         &lt;element name="DocumentExchangeDetails" type="{MDA_Common_Types}DocumentExchangeDetailsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DocumentHeaderType", propOrder = {
    "documentReference",
    "documentExchangeDetails"
})
public class DocumentHeaderType {

    @XmlElement(name = "DocumentReference", required = true)
    protected DocumentReferenceType documentReference;
    @XmlElement(name = "DocumentExchangeDetails", required = true)
    protected DocumentExchangeDetailsType documentExchangeDetails;

    /**
     * Gets the value of the documentReference property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentReferenceType }
     *     
     */
    public DocumentReferenceType getDocumentReference() {
        return documentReference;
    }

    /**
     * Sets the value of the documentReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentReferenceType }
     *     
     */
    public void setDocumentReference(DocumentReferenceType value) {
        this.documentReference = value;
    }

    /**
     * Gets the value of the documentExchangeDetails property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentExchangeDetailsType }
     *     
     */
    public DocumentExchangeDetailsType getDocumentExchangeDetails() {
        return documentExchangeDetails;
    }

    /**
     * Sets the value of the documentExchangeDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentExchangeDetailsType }
     *     
     */
    public void setDocumentExchangeDetails(DocumentExchangeDetailsType value) {
        this.documentExchangeDetails = value;
    }

}
