//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.21 at 03:15:08 AM EAT 
//


package xmlparser.kensws.condoc1_v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DocumentReferenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DocumentReferenceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DocumentType" type="{MDA_Common_Types}DocumentTypeIdentifierType"/>
 *         &lt;element name="DocumentName" type="{MDA_Common_Types}DocumentNameTextType" minOccurs="0"/>
 *         &lt;element name="DocumentNumber" type="{MDA_Common_Types}DocumentIdentificationIdentifierType" minOccurs="0"/>
 *         &lt;element name="CommonRefNumber" type="{MDA_Common_Types}DocumentIdentificationIdentifierType" minOccurs="0"/>
 *         &lt;element name="MessageType" type="{MDA_Common_Types}MessageType"/>
 *         &lt;element name="SenderID" type="{MDA_Common_Types}SendingReceivingNotifyPartyType"/>
 *         &lt;element name="RegimeCode" type="{MDA_Common_Types}SendingReceivingNotifyPartyType"/>
 *         &lt;element name="CMSRegimeCode" type="{MDA_Common_Types}CMSRegimeCodeType"/>
 *         &lt;element name="ApprovalCategory" type="{MDA_Common_Types}SendingReceivingNotifyPartyType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DocumentReferenceType", propOrder = {
    "documentType",
    "documentName",
    "documentNumber",
    "commonRefNumber",
    "messageType",
    "senderID",
    "regimeCode",
    "cmsRegimeCode",
    "approvalCategory"
})
public class DocumentReferenceType {

    @XmlElement(name = "DocumentType", required = true)
    protected String documentType;
    @XmlElement(name = "DocumentName")
    protected String documentName;
    @XmlElement(name = "DocumentNumber")
    protected String documentNumber;
    @XmlElement(name = "CommonRefNumber")
    protected String commonRefNumber;
    @XmlElement(name = "MessageType", required = true)
    protected String messageType;
    @XmlElement(name = "SenderID", required = true)
    protected String senderID;
    @XmlElement(name = "RegimeCode", required = true)
    protected String regimeCode;
    @XmlElement(name = "CMSRegimeCode", required = true)
    protected String cmsRegimeCode;
    @XmlElement(name = "ApprovalCategory", required = true)
    protected String approvalCategory;

    /**
     * Gets the value of the documentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentType() {
        return documentType;
    }

    /**
     * Sets the value of the documentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentType(String value) {
        this.documentType = value;
    }

    /**
     * Gets the value of the documentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentName() {
        return documentName;
    }

    /**
     * Sets the value of the documentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentName(String value) {
        this.documentName = value;
    }

    /**
     * Gets the value of the documentNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentNumber() {
        return documentNumber;
    }

    /**
     * Sets the value of the documentNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentNumber(String value) {
        this.documentNumber = value;
    }

    /**
     * Gets the value of the commonRefNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommonRefNumber() {
        return commonRefNumber;
    }

    /**
     * Sets the value of the commonRefNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommonRefNumber(String value) {
        this.commonRefNumber = value;
    }

    /**
     * Gets the value of the messageType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageType() {
        return messageType;
    }

    /**
     * Sets the value of the messageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageType(String value) {
        this.messageType = value;
    }

    /**
     * Gets the value of the senderID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderID() {
        return senderID;
    }

    /**
     * Sets the value of the senderID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderID(String value) {
        this.senderID = value;
    }

    /**
     * Gets the value of the regimeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegimeCode() {
        return regimeCode;
    }

    /**
     * Sets the value of the regimeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegimeCode(String value) {
        this.regimeCode = value;
    }

    /**
     * Gets the value of the cmsRegimeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCMSRegimeCode() {
        return cmsRegimeCode;
    }

    /**
     * Sets the value of the cmsRegimeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCMSRegimeCode(String value) {
        this.cmsRegimeCode = value;
    }

    /**
     * Gets the value of the approvalCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprovalCategory() {
        return approvalCategory;
    }

    /**
     * Sets the value of the approvalCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprovalCategory(String value) {
        this.approvalCategory = value;
    }

}
