//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.21 at 03:24:53 AM EAT 
//


package xmlparser.kensws.condoc1_v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DocumentDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DocumentDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ConsignmentDocDetails">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CDStandard" type="{MDA_Common_Types}StandardDetailsType"/>
 *                   &lt;element name="ApprovalDetails" type="{}ApprovalDetailsType" minOccurs="0"/>
 *                   &lt;element name="CDImporter" type="{MDA_Common_Types}EXIM_CON_Type"/>
 *                   &lt;element name="CDConsignee" type="{MDA_Common_Types}EXIM_CON_Type"/>
 *                   &lt;element name="CDExporter" type="{MDA_Common_Types}EXIM_CON_Type"/>
 *                   &lt;element name="CDConsignor" type="{MDA_Common_Types}EXIM_CON_Type"/>
 *                   &lt;element name="CDTransport" type="{MDA_Common_Types}TransportType"/>
 *                   &lt;element name="PGAHeaderFields" type="{}KEPHISHeaderFieldsType" minOccurs="0"/>
 *                   &lt;element name="CDHeaderOne" type="{MDA_Common_Types}HeaderOneType"/>
 *                   &lt;element name="CDHeaderTwo" type="{MDA_Common_Types}HeaderTwoType" minOccurs="0"/>
 *                   &lt;element name="CDStandardTwo" type="{MDA_Common_Types}StandardDetailsTwoType"/>
 *                   &lt;element name="CDHdrAdditional" type="{MDA_Common_Types}HdrAdditionalDetailsType" minOccurs="0"/>
 *                   &lt;element name="CDProductDetails" type="{}ProductDetailsType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DocumentDetailsType", namespace = "", propOrder = {
    "consignmentDocDetails"
})
public class DocumentDetailsType {

    @XmlElement(name = "ConsignmentDocDetails", required = true)
    protected DocumentDetailsType.ConsignmentDocDetails consignmentDocDetails;

    /**
     * Gets the value of the consignmentDocDetails property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentDetailsType.ConsignmentDocDetails }
     *     
     */
    public DocumentDetailsType.ConsignmentDocDetails getConsignmentDocDetails() {
        return consignmentDocDetails;
    }

    /**
     * Sets the value of the consignmentDocDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentDetailsType.ConsignmentDocDetails }
     *     
     */
    public void setConsignmentDocDetails(DocumentDetailsType.ConsignmentDocDetails value) {
        this.consignmentDocDetails = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CDStandard" type="{MDA_Common_Types}StandardDetailsType"/>
     *         &lt;element name="ApprovalDetails" type="{}ApprovalDetailsType" minOccurs="0"/>
     *         &lt;element name="CDImporter" type="{MDA_Common_Types}EXIM_CON_Type"/>
     *         &lt;element name="CDConsignee" type="{MDA_Common_Types}EXIM_CON_Type"/>
     *         &lt;element name="CDExporter" type="{MDA_Common_Types}EXIM_CON_Type"/>
     *         &lt;element name="CDConsignor" type="{MDA_Common_Types}EXIM_CON_Type"/>
     *         &lt;element name="CDTransport" type="{MDA_Common_Types}TransportType"/>
     *         &lt;element name="PGAHeaderFields" type="{}KEPHISHeaderFieldsType" minOccurs="0"/>
     *         &lt;element name="CDHeaderOne" type="{MDA_Common_Types}HeaderOneType"/>
     *         &lt;element name="CDHeaderTwo" type="{MDA_Common_Types}HeaderTwoType" minOccurs="0"/>
     *         &lt;element name="CDStandardTwo" type="{MDA_Common_Types}StandardDetailsTwoType"/>
     *         &lt;element name="CDHdrAdditional" type="{MDA_Common_Types}HdrAdditionalDetailsType" minOccurs="0"/>
     *         &lt;element name="CDProductDetails" type="{}ProductDetailsType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cdStandard",
        "approvalDetails",
        "cdImporter",
        "cdConsignee",
        "cdExporter",
        "cdConsignor",
        "cdTransport",
        "pgaHeaderFields",
        "cdHeaderOne",
        "cdHeaderTwo",
        "cdStandardTwo",
        "cdHdrAdditional",
        "cdProductDetails"
    })
    public static class ConsignmentDocDetails {

        @XmlElement(name = "CDStandard", required = true)
        protected StandardDetailsType cdStandard;
        @XmlElement(name = "ApprovalDetails")
        protected ApprovalDetailsType approvalDetails;
        @XmlElement(name = "CDImporter", required = true)
        protected EXIMCONType cdImporter;
        @XmlElement(name = "CDConsignee", required = true)
        protected EXIMCONType cdConsignee;
        @XmlElement(name = "CDExporter", required = true)
        protected EXIMCONType cdExporter;
        @XmlElement(name = "CDConsignor", required = true)
        protected EXIMCONType cdConsignor;
        @XmlElement(name = "CDTransport", required = true)
        protected TransportType cdTransport;
        @XmlElement(name = "PGAHeaderFields")
        protected KEPHISHeaderFieldsType pgaHeaderFields;
        @XmlElement(name = "CDHeaderOne", required = true)
        protected HeaderOneType cdHeaderOne;
        @XmlElement(name = "CDHeaderTwo")
        protected HeaderTwoType cdHeaderTwo;
        @XmlElement(name = "CDStandardTwo", required = true)
        protected StandardDetailsTwoType cdStandardTwo;
        @XmlElement(name = "CDHdrAdditional")
        protected HdrAdditionalDetailsType cdHdrAdditional;
        @XmlElement(name = "CDProductDetails", required = true)
        protected ProductDetailsType cdProductDetails;

        /**
         * Gets the value of the cdStandard property.
         * 
         * @return
         *     possible object is
         *     {@link StandardDetailsType }
         *     
         */
        public StandardDetailsType getCDStandard() {
            return cdStandard;
        }

        /**
         * Sets the value of the cdStandard property.
         * 
         * @param value
         *     allowed object is
         *     {@link StandardDetailsType }
         *     
         */
        public void setCDStandard(StandardDetailsType value) {
            this.cdStandard = value;
        }

        /**
         * Gets the value of the approvalDetails property.
         * 
         * @return
         *     possible object is
         *     {@link ApprovalDetailsType }
         *     
         */
        public ApprovalDetailsType getApprovalDetails() {
            return approvalDetails;
        }

        /**
         * Sets the value of the approvalDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link ApprovalDetailsType }
         *     
         */
        public void setApprovalDetails(ApprovalDetailsType value) {
            this.approvalDetails = value;
        }

        /**
         * Gets the value of the cdImporter property.
         * 
         * @return
         *     possible object is
         *     {@link EXIMCONType }
         *     
         */
        public EXIMCONType getCDImporter() {
            return cdImporter;
        }

        /**
         * Sets the value of the cdImporter property.
         * 
         * @param value
         *     allowed object is
         *     {@link EXIMCONType }
         *     
         */
        public void setCDImporter(EXIMCONType value) {
            this.cdImporter = value;
        }

        /**
         * Gets the value of the cdConsignee property.
         * 
         * @return
         *     possible object is
         *     {@link EXIMCONType }
         *     
         */
        public EXIMCONType getCDConsignee() {
            return cdConsignee;
        }

        /**
         * Sets the value of the cdConsignee property.
         * 
         * @param value
         *     allowed object is
         *     {@link EXIMCONType }
         *     
         */
        public void setCDConsignee(EXIMCONType value) {
            this.cdConsignee = value;
        }

        /**
         * Gets the value of the cdExporter property.
         * 
         * @return
         *     possible object is
         *     {@link EXIMCONType }
         *     
         */
        public EXIMCONType getCDExporter() {
            return cdExporter;
        }

        /**
         * Sets the value of the cdExporter property.
         * 
         * @param value
         *     allowed object is
         *     {@link EXIMCONType }
         *     
         */
        public void setCDExporter(EXIMCONType value) {
            this.cdExporter = value;
        }

        /**
         * Gets the value of the cdConsignor property.
         * 
         * @return
         *     possible object is
         *     {@link EXIMCONType }
         *     
         */
        public EXIMCONType getCDConsignor() {
            return cdConsignor;
        }

        /**
         * Sets the value of the cdConsignor property.
         * 
         * @param value
         *     allowed object is
         *     {@link EXIMCONType }
         *     
         */
        public void setCDConsignor(EXIMCONType value) {
            this.cdConsignor = value;
        }

        /**
         * Gets the value of the cdTransport property.
         * 
         * @return
         *     possible object is
         *     {@link TransportType }
         *     
         */
        public TransportType getCDTransport() {
            return cdTransport;
        }

        /**
         * Sets the value of the cdTransport property.
         * 
         * @param value
         *     allowed object is
         *     {@link TransportType }
         *     
         */
        public void setCDTransport(TransportType value) {
            this.cdTransport = value;
        }

        /**
         * Gets the value of the pgaHeaderFields property.
         * 
         * @return
         *     possible object is
         *     {@link KEPHISHeaderFieldsType }
         *     
         */
        public KEPHISHeaderFieldsType getPGAHeaderFields() {
            return pgaHeaderFields;
        }

        /**
         * Sets the value of the pgaHeaderFields property.
         * 
         * @param value
         *     allowed object is
         *     {@link KEPHISHeaderFieldsType }
         *     
         */
        public void setPGAHeaderFields(KEPHISHeaderFieldsType value) {
            this.pgaHeaderFields = value;
        }

        /**
         * Gets the value of the cdHeaderOne property.
         * 
         * @return
         *     possible object is
         *     {@link HeaderOneType }
         *     
         */
        public HeaderOneType getCDHeaderOne() {
            return cdHeaderOne;
        }

        /**
         * Sets the value of the cdHeaderOne property.
         * 
         * @param value
         *     allowed object is
         *     {@link HeaderOneType }
         *     
         */
        public void setCDHeaderOne(HeaderOneType value) {
            this.cdHeaderOne = value;
        }

        /**
         * Gets the value of the cdHeaderTwo property.
         * 
         * @return
         *     possible object is
         *     {@link HeaderTwoType }
         *     
         */
        public HeaderTwoType getCDHeaderTwo() {
            return cdHeaderTwo;
        }

        /**
         * Sets the value of the cdHeaderTwo property.
         * 
         * @param value
         *     allowed object is
         *     {@link HeaderTwoType }
         *     
         */
        public void setCDHeaderTwo(HeaderTwoType value) {
            this.cdHeaderTwo = value;
        }

        /**
         * Gets the value of the cdStandardTwo property.
         * 
         * @return
         *     possible object is
         *     {@link StandardDetailsTwoType }
         *     
         */
        public StandardDetailsTwoType getCDStandardTwo() {
            return cdStandardTwo;
        }

        /**
         * Sets the value of the cdStandardTwo property.
         * 
         * @param value
         *     allowed object is
         *     {@link StandardDetailsTwoType }
         *     
         */
        public void setCDStandardTwo(StandardDetailsTwoType value) {
            this.cdStandardTwo = value;
        }

        /**
         * Gets the value of the cdHdrAdditional property.
         * 
         * @return
         *     possible object is
         *     {@link HdrAdditionalDetailsType }
         *     
         */
        public HdrAdditionalDetailsType getCDHdrAdditional() {
            return cdHdrAdditional;
        }

        /**
         * Sets the value of the cdHdrAdditional property.
         * 
         * @param value
         *     allowed object is
         *     {@link HdrAdditionalDetailsType }
         *     
         */
        public void setCDHdrAdditional(HdrAdditionalDetailsType value) {
            this.cdHdrAdditional = value;
        }

        /**
         * Gets the value of the cdProductDetails property.
         * 
         * @return
         *     possible object is
         *     {@link ProductDetailsType }
         *     
         */
        public ProductDetailsType getCDProductDetails() {
            return cdProductDetails;
        }

        /**
         * Sets the value of the cdProductDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link ProductDetailsType }
         *     
         */
        public void setCDProductDetails(ProductDetailsType value) {
            this.cdProductDetails = value;
        }

    }

}
