//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.21 at 03:15:08 AM EAT 
//


package xmlparser.kensws.condoc1_v1_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EXIMDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EXIMDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ImporterTIN" type="{MDA_Common_Types}ImporterTINType"/>
 *         &lt;element name="ImporterName" type="{MDA_Common_Types}ImporterNameType"/>
 *         &lt;element name="ImporterADD" type="{MDA_Common_Types}ImporterADDType" maxOccurs="2"/>
 *         &lt;element name="ImporterCTY" type="{MDA_Common_Types}ImporterCTYType" minOccurs="0"/>
 *         &lt;element name="ImporterCTYDESC" type="{MDA_Common_Types}ImporterCTYDESC" minOccurs="0"/>
 *         &lt;element name="ImporterContactPerson" type="{MDA_Common_Types}ImporterContactPersonType"/>
 *         &lt;element name="ImporterContactPersonDES" type="{MDA_Common_Types}ImporterContactPersonDESType" minOccurs="0"/>
 *         &lt;element name="ImporterTELFAX" type="{MDA_Common_Types}ImporterTELFAXType" minOccurs="0"/>
 *         &lt;element name="ImporterCON" type="{MDA_Common_Types}ImporterCONType" minOccurs="0"/>
 *         &lt;element name="ExporterTIN" type="{MDA_Common_Types}ExporterTINType"/>
 *         &lt;element name="ExporterName" type="{MDA_Common_Types}ExporterNameType"/>
 *         &lt;element name="ExporterADD" type="{MDA_Common_Types}ExporterADDType" maxOccurs="2"/>
 *         &lt;element name="ExporterCTY" type="{MDA_Common_Types}ExporterCTYType" minOccurs="0"/>
 *         &lt;element name="ExporterCTYDESC" type="{MDA_Common_Types}ExporterCTYDESC" minOccurs="0"/>
 *         &lt;element name="ExporterContactPerson" type="{MDA_Common_Types}ExporterContactPersonType"/>
 *         &lt;element name="ExporterContactPersonDES" type="{MDA_Common_Types}ExporterContactPersonDESType" minOccurs="0"/>
 *         &lt;element name="ExporterTELFAX" type="{MDA_Common_Types}ExporterTELFAXType" minOccurs="0"/>
 *         &lt;element name="ExporterCON" type="{MDA_Common_Types}ExporterCONType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EXIMDetailsType", propOrder = {
    "importerTIN",
    "importerName",
    "importerADD",
    "importerCTY",
    "importerCTYDESC",
    "importerContactPerson",
    "importerContactPersonDES",
    "importerTELFAX",
    "importerCON",
    "exporterTIN",
    "exporterName",
    "exporterADD",
    "exporterCTY",
    "exporterCTYDESC",
    "exporterContactPerson",
    "exporterContactPersonDES",
    "exporterTELFAX",
    "exporterCON"
})
public class EXIMDetailsType {

    @XmlElement(name = "ImporterTIN", required = true)
    protected String importerTIN;
    @XmlElement(name = "ImporterName", required = true)
    protected String importerName;
    @XmlElement(name = "ImporterADD", required = true)
    protected List<String> importerADD;
    @XmlElement(name = "ImporterCTY")
    protected String importerCTY;
    @XmlElement(name = "ImporterCTYDESC")
    protected String importerCTYDESC;
    @XmlElement(name = "ImporterContactPerson", required = true)
    protected String importerContactPerson;
    @XmlElement(name = "ImporterContactPersonDES")
    protected String importerContactPersonDES;
    @XmlElement(name = "ImporterTELFAX")
    protected String importerTELFAX;
    @XmlElement(name = "ImporterCON")
    protected String importerCON;
    @XmlElement(name = "ExporterTIN", required = true)
    protected String exporterTIN;
    @XmlElement(name = "ExporterName", required = true)
    protected String exporterName;
    @XmlElement(name = "ExporterADD", required = true)
    protected List<String> exporterADD;
    @XmlElement(name = "ExporterCTY")
    protected String exporterCTY;
    @XmlElement(name = "ExporterCTYDESC")
    protected String exporterCTYDESC;
    @XmlElement(name = "ExporterContactPerson", required = true)
    protected String exporterContactPerson;
    @XmlElement(name = "ExporterContactPersonDES")
    protected String exporterContactPersonDES;
    @XmlElement(name = "ExporterTELFAX")
    protected String exporterTELFAX;
    @XmlElement(name = "ExporterCON")
    protected String exporterCON;

    /**
     * Gets the value of the importerTIN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImporterTIN() {
        return importerTIN;
    }

    /**
     * Sets the value of the importerTIN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImporterTIN(String value) {
        this.importerTIN = value;
    }

    /**
     * Gets the value of the importerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImporterName() {
        return importerName;
    }

    /**
     * Sets the value of the importerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImporterName(String value) {
        this.importerName = value;
    }

    /**
     * Gets the value of the importerADD property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the importerADD property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImporterADD().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getImporterADD() {
        if (importerADD == null) {
            importerADD = new ArrayList<String>();
        }
        return this.importerADD;
    }

    /**
     * Gets the value of the importerCTY property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImporterCTY() {
        return importerCTY;
    }

    /**
     * Sets the value of the importerCTY property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImporterCTY(String value) {
        this.importerCTY = value;
    }

    /**
     * Gets the value of the importerCTYDESC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImporterCTYDESC() {
        return importerCTYDESC;
    }

    /**
     * Sets the value of the importerCTYDESC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImporterCTYDESC(String value) {
        this.importerCTYDESC = value;
    }

    /**
     * Gets the value of the importerContactPerson property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImporterContactPerson() {
        return importerContactPerson;
    }

    /**
     * Sets the value of the importerContactPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImporterContactPerson(String value) {
        this.importerContactPerson = value;
    }

    /**
     * Gets the value of the importerContactPersonDES property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImporterContactPersonDES() {
        return importerContactPersonDES;
    }

    /**
     * Sets the value of the importerContactPersonDES property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImporterContactPersonDES(String value) {
        this.importerContactPersonDES = value;
    }

    /**
     * Gets the value of the importerTELFAX property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImporterTELFAX() {
        return importerTELFAX;
    }

    /**
     * Sets the value of the importerTELFAX property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImporterTELFAX(String value) {
        this.importerTELFAX = value;
    }

    /**
     * Gets the value of the importerCON property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImporterCON() {
        return importerCON;
    }

    /**
     * Sets the value of the importerCON property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImporterCON(String value) {
        this.importerCON = value;
    }

    /**
     * Gets the value of the exporterTIN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExporterTIN() {
        return exporterTIN;
    }

    /**
     * Sets the value of the exporterTIN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExporterTIN(String value) {
        this.exporterTIN = value;
    }

    /**
     * Gets the value of the exporterName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExporterName() {
        return exporterName;
    }

    /**
     * Sets the value of the exporterName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExporterName(String value) {
        this.exporterName = value;
    }

    /**
     * Gets the value of the exporterADD property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the exporterADD property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExporterADD().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getExporterADD() {
        if (exporterADD == null) {
            exporterADD = new ArrayList<String>();
        }
        return this.exporterADD;
    }

    /**
     * Gets the value of the exporterCTY property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExporterCTY() {
        return exporterCTY;
    }

    /**
     * Sets the value of the exporterCTY property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExporterCTY(String value) {
        this.exporterCTY = value;
    }

    /**
     * Gets the value of the exporterCTYDESC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExporterCTYDESC() {
        return exporterCTYDESC;
    }

    /**
     * Sets the value of the exporterCTYDESC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExporterCTYDESC(String value) {
        this.exporterCTYDESC = value;
    }

    /**
     * Gets the value of the exporterContactPerson property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExporterContactPerson() {
        return exporterContactPerson;
    }

    /**
     * Sets the value of the exporterContactPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExporterContactPerson(String value) {
        this.exporterContactPerson = value;
    }

    /**
     * Gets the value of the exporterContactPersonDES property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExporterContactPersonDES() {
        return exporterContactPersonDES;
    }

    /**
     * Sets the value of the exporterContactPersonDES property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExporterContactPersonDES(String value) {
        this.exporterContactPersonDES = value;
    }

    /**
     * Gets the value of the exporterTELFAX property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExporterTELFAX() {
        return exporterTELFAX;
    }

    /**
     * Sets the value of the exporterTELFAX property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExporterTELFAX(String value) {
        this.exporterTELFAX = value;
    }

    /**
     * Gets the value of the exporterCON property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExporterCON() {
        return exporterCON;
    }

    /**
     * Sets the value of the exporterCON property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExporterCON(String value) {
        this.exporterCON = value;
    }

}
