//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.21 at 03:15:08 AM EAT 
//


package xmlparser.kensws.condoc1_v1_0;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for HeaderOneType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HeaderOneType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ForeignCurrencyCode" type="{MDA_Common_Types}CurrencyCodeType"/>
 *         &lt;element name="ForexRate" type="{MDA_Common_Types}ForexRateType"/>
 *         &lt;element name="FOBFCY" type="{MDA_Common_Types}FCYType"/>
 *         &lt;element name="FreightFCY" type="{MDA_Common_Types}FCYType" minOccurs="0"/>
 *         &lt;element name="InsuranceFCY" type="{MDA_Common_Types}FCYType" minOccurs="0"/>
 *         &lt;element name="OtherChargesFCY" type="{MDA_Common_Types}FCYType" minOccurs="0"/>
 *         &lt;element name="CIFFCY" type="{MDA_Common_Types}FCYType"/>
 *         &lt;element name="FOBNCY" type="{MDA_Common_Types}NCYType"/>
 *         &lt;element name="FreightNCY" type="{MDA_Common_Types}NCYType" minOccurs="0"/>
 *         &lt;element name="InsuranceNCY" type="{MDA_Common_Types}NCYType" minOccurs="0"/>
 *         &lt;element name="OtherChargesNCY" type="{MDA_Common_Types}NCYType" minOccurs="0"/>
 *         &lt;element name="CIFNCY" type="{MDA_Common_Types}NCYType"/>
 *         &lt;element name="INCOTerms" type="{MDA_Common_Types}INCOTermsType"/>
 *         &lt;element name="TransactionTerms" type="{MDA_Common_Types}TransactionTermsType" minOccurs="0"/>
 *         &lt;element name="COMESA" type="{MDA_Common_Types}COMESAType" minOccurs="0"/>
 *         &lt;element name="InvoiceDate" type="{MDA_Common_Types}DateType"/>
 *         &lt;element name="InvoiceNumber" type="{MDA_Common_Types}InvoiceNoType"/>
 *         &lt;element name="CountryOfSupply" type="{MDA_Common_Types}CountryType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HeaderOneType", propOrder = {
    "foreignCurrencyCode",
    "forexRate",
    "fobfcy",
    "freightFCY",
    "insuranceFCY",
    "otherChargesFCY",
    "ciffcy",
    "fobncy",
    "freightNCY",
    "insuranceNCY",
    "otherChargesNCY",
    "cifncy",
    "incoTerms",
    "transactionTerms",
    "comesa",
    "invoiceDate",
    "invoiceNumber",
    "countryOfSupply"
})
public class HeaderOneType {

    @XmlElement(name = "ForeignCurrencyCode", required = true)
    protected String foreignCurrencyCode;
    @XmlElement(name = "ForexRate", required = true)
    protected BigDecimal forexRate;
    @XmlElement(name = "FOBFCY", required = true)
    protected BigDecimal fobfcy;
    @XmlElement(name = "FreightFCY")
    protected BigDecimal freightFCY;
    @XmlElement(name = "InsuranceFCY")
    protected BigDecimal insuranceFCY;
    @XmlElement(name = "OtherChargesFCY")
    protected BigDecimal otherChargesFCY;
    @XmlElement(name = "CIFFCY", required = true)
    protected BigDecimal ciffcy;
    @XmlElement(name = "FOBNCY", required = true)
    protected BigDecimal fobncy;
    @XmlElement(name = "FreightNCY")
    protected BigDecimal freightNCY;
    @XmlElement(name = "InsuranceNCY")
    protected BigDecimal insuranceNCY;
    @XmlElement(name = "OtherChargesNCY")
    protected BigDecimal otherChargesNCY;
    @XmlElement(name = "CIFNCY", required = true)
    protected BigDecimal cifncy;
    @XmlElement(name = "INCOTerms", required = true)
    protected String incoTerms;
    @XmlElement(name = "TransactionTerms")
    protected String transactionTerms;
    @XmlElement(name = "COMESA")
    protected String comesa;
    @XmlElement(name = "InvoiceDate", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String invoiceDate;
    @XmlElement(name = "InvoiceNumber", required = true)
    protected String invoiceNumber;
    @XmlElement(name = "CountryOfSupply", required = true)
    protected String countryOfSupply;

    /**
     * Gets the value of the foreignCurrencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForeignCurrencyCode() {
        return foreignCurrencyCode;
    }

    /**
     * Sets the value of the foreignCurrencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForeignCurrencyCode(String value) {
        this.foreignCurrencyCode = value;
    }

    /**
     * Gets the value of the forexRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getForexRate() {
        return forexRate;
    }

    /**
     * Sets the value of the forexRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setForexRate(BigDecimal value) {
        this.forexRate = value;
    }

    /**
     * Gets the value of the fobfcy property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFOBFCY() {
        return fobfcy;
    }

    /**
     * Sets the value of the fobfcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFOBFCY(BigDecimal value) {
        this.fobfcy = value;
    }

    /**
     * Gets the value of the freightFCY property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFreightFCY() {
        return freightFCY;
    }

    /**
     * Sets the value of the freightFCY property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFreightFCY(BigDecimal value) {
        this.freightFCY = value;
    }

    /**
     * Gets the value of the insuranceFCY property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInsuranceFCY() {
        return insuranceFCY;
    }

    /**
     * Sets the value of the insuranceFCY property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInsuranceFCY(BigDecimal value) {
        this.insuranceFCY = value;
    }

    /**
     * Gets the value of the otherChargesFCY property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOtherChargesFCY() {
        return otherChargesFCY;
    }

    /**
     * Sets the value of the otherChargesFCY property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOtherChargesFCY(BigDecimal value) {
        this.otherChargesFCY = value;
    }

    /**
     * Gets the value of the ciffcy property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCIFFCY() {
        return ciffcy;
    }

    /**
     * Sets the value of the ciffcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCIFFCY(BigDecimal value) {
        this.ciffcy = value;
    }

    /**
     * Gets the value of the fobncy property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFOBNCY() {
        return fobncy;
    }

    /**
     * Sets the value of the fobncy property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFOBNCY(BigDecimal value) {
        this.fobncy = value;
    }

    /**
     * Gets the value of the freightNCY property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFreightNCY() {
        return freightNCY;
    }

    /**
     * Sets the value of the freightNCY property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFreightNCY(BigDecimal value) {
        this.freightNCY = value;
    }

    /**
     * Gets the value of the insuranceNCY property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInsuranceNCY() {
        return insuranceNCY;
    }

    /**
     * Sets the value of the insuranceNCY property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInsuranceNCY(BigDecimal value) {
        this.insuranceNCY = value;
    }

    /**
     * Gets the value of the otherChargesNCY property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOtherChargesNCY() {
        return otherChargesNCY;
    }

    /**
     * Sets the value of the otherChargesNCY property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOtherChargesNCY(BigDecimal value) {
        this.otherChargesNCY = value;
    }

    /**
     * Gets the value of the cifncy property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCIFNCY() {
        return cifncy;
    }

    /**
     * Sets the value of the cifncy property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCIFNCY(BigDecimal value) {
        this.cifncy = value;
    }

    /**
     * Gets the value of the incoTerms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINCOTerms() {
        return incoTerms;
    }

    /**
     * Sets the value of the incoTerms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINCOTerms(String value) {
        this.incoTerms = value;
    }

    /**
     * Gets the value of the transactionTerms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionTerms() {
        return transactionTerms;
    }

    /**
     * Sets the value of the transactionTerms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionTerms(String value) {
        this.transactionTerms = value;
    }

    /**
     * Gets the value of the comesa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOMESA() {
        return comesa;
    }

    /**
     * Sets the value of the comesa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOMESA(String value) {
        this.comesa = value;
    }

    /**
     * Gets the value of the invoiceDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoiceDate() {
        return invoiceDate;
    }

    /**
     * Sets the value of the invoiceDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoiceDate(String value) {
        this.invoiceDate = value;
    }

    /**
     * Gets the value of the invoiceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoiceNumber() {
        return invoiceNumber;
    }

    /**
     * Sets the value of the invoiceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoiceNumber(String value) {
        this.invoiceNumber = value;
    }

    /**
     * Gets the value of the countryOfSupply property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryOfSupply() {
        return countryOfSupply;
    }

    /**
     * Sets the value of the countryOfSupply property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryOfSupply(String value) {
        this.countryOfSupply = value;
    }

}
