//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.21 at 03:24:53 AM EAT 
//


package xmlparser.kensws.condoc1_v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ItemCommodityDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ItemCommodityDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CommonName" type="{}CommonNameType" minOccurs="0"/>
 *         &lt;element name="OrganismStrain" type="{}OrganismStrainType" minOccurs="0"/>
 *         &lt;element name="TreatmentInformation" type="{}TreatmentInformationType" minOccurs="0"/>
 *         &lt;element name="TreatmentDate" type="{}DateTimeFormatType" minOccurs="0"/>
 *         &lt;element name="DurationsAndTemperature" type="{}DurationsAndTemperatureType" minOccurs="0"/>
 *         &lt;element name="ChemicalsActiveIngredients" type="{}ChemicalsActiveIngredientsType" minOccurs="0"/>
 *         &lt;element name="ConcentrationActiveIngredients" type="{}ConcentrationActiveIngredientsType" minOccurs="0"/>
 *         &lt;element name="SeedReferenceNo" type="{}SeedReferenceNoType" minOccurs="0"/>
 *         &lt;element name="ProducerDetails" type="{}ProducerDetailsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItemCommodityDetailsType", namespace = "", propOrder = {
    "commonName",
    "organismStrain",
    "treatmentInformation",
    "treatmentDate",
    "durationsAndTemperature",
    "chemicalsActiveIngredients",
    "concentrationActiveIngredients",
    "seedReferenceNo",
    "producerDetails"
})
public class ItemCommodityDetailsType {

    @XmlElement(name = "CommonName")
    protected String commonName;
    @XmlElement(name = "OrganismStrain")
    protected String organismStrain;
    @XmlElement(name = "TreatmentInformation")
    protected String treatmentInformation;
    @XmlElement(name = "TreatmentDate")
    protected String treatmentDate;
    @XmlElement(name = "DurationsAndTemperature")
    protected String durationsAndTemperature;
    @XmlElement(name = "ChemicalsActiveIngredients")
    protected String chemicalsActiveIngredients;
    @XmlElement(name = "ConcentrationActiveIngredients")
    protected String concentrationActiveIngredients;
    @XmlElement(name = "SeedReferenceNo")
    protected String seedReferenceNo;
    @XmlElement(name = "ProducerDetails")
    protected String producerDetails;

    /**
     * Gets the value of the commonName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommonName() {
        return commonName;
    }

    /**
     * Sets the value of the commonName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommonName(String value) {
        this.commonName = value;
    }

    /**
     * Gets the value of the organismStrain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganismStrain() {
        return organismStrain;
    }

    /**
     * Sets the value of the organismStrain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganismStrain(String value) {
        this.organismStrain = value;
    }

    /**
     * Gets the value of the treatmentInformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTreatmentInformation() {
        return treatmentInformation;
    }

    /**
     * Sets the value of the treatmentInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTreatmentInformation(String value) {
        this.treatmentInformation = value;
    }

    /**
     * Gets the value of the treatmentDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTreatmentDate() {
        return treatmentDate;
    }

    /**
     * Sets the value of the treatmentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTreatmentDate(String value) {
        this.treatmentDate = value;
    }

    /**
     * Gets the value of the durationsAndTemperature property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDurationsAndTemperature() {
        return durationsAndTemperature;
    }

    /**
     * Sets the value of the durationsAndTemperature property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDurationsAndTemperature(String value) {
        this.durationsAndTemperature = value;
    }

    /**
     * Gets the value of the chemicalsActiveIngredients property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChemicalsActiveIngredients() {
        return chemicalsActiveIngredients;
    }

    /**
     * Sets the value of the chemicalsActiveIngredients property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChemicalsActiveIngredients(String value) {
        this.chemicalsActiveIngredients = value;
    }

    /**
     * Gets the value of the concentrationActiveIngredients property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConcentrationActiveIngredients() {
        return concentrationActiveIngredients;
    }

    /**
     * Sets the value of the concentrationActiveIngredients property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConcentrationActiveIngredients(String value) {
        this.concentrationActiveIngredients = value;
    }

    /**
     * Gets the value of the seedReferenceNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeedReferenceNo() {
        return seedReferenceNo;
    }

    /**
     * Sets the value of the seedReferenceNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeedReferenceNo(String value) {
        this.seedReferenceNo = value;
    }

    /**
     * Gets the value of the producerDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProducerDetails() {
        return producerDetails;
    }

    /**
     * Sets the value of the producerDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProducerDetails(String value) {
        this.producerDetails = value;
    }

}
