//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.21 at 03:24:53 AM EAT 
//


package xmlparser.kensws.condoc1_v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KEPHISHeaderFieldsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KEPHISHeaderFieldsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CollectionOffice" type="{}CollectionOfficeType"/>
 *         &lt;element name="CertificationCategory" type="{}CertificationCategoryType" minOccurs="0"/>
 *         &lt;element name="PlaceOfApplication" type="{}PlaceOfApplicationType" minOccurs="0"/>
 *         &lt;element name="PreferredInspectionDate" type="{}DateTimeFormatType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KEPHISHeaderFieldsType", namespace = "", propOrder = {
    "collectionOffice",
    "certificationCategory",
    "placeOfApplication",
    "preferredInspectionDate"
})
public class KEPHISHeaderFieldsType {

    @XmlElement(name = "CollectionOffice", required = true)
    protected String collectionOffice;
    @XmlElement(name = "CertificationCategory")
    protected String certificationCategory;
    @XmlElement(name = "PlaceOfApplication")
    protected String placeOfApplication;
    @XmlElement(name = "PreferredInspectionDate")
    protected String preferredInspectionDate;

    /**
     * Gets the value of the collectionOffice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCollectionOffice() {
        return collectionOffice;
    }

    /**
     * Sets the value of the collectionOffice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCollectionOffice(String value) {
        this.collectionOffice = value;
    }

    /**
     * Gets the value of the certificationCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertificationCategory() {
        return certificationCategory;
    }

    /**
     * Sets the value of the certificationCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertificationCategory(String value) {
        this.certificationCategory = value;
    }

    /**
     * Gets the value of the placeOfApplication property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlaceOfApplication() {
        return placeOfApplication;
    }

    /**
     * Sets the value of the placeOfApplication property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlaceOfApplication(String value) {
        this.placeOfApplication = value;
    }

    /**
     * Gets the value of the preferredInspectionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreferredInspectionDate() {
        return preferredInspectionDate;
    }

    /**
     * Sets the value of the preferredInspectionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreferredInspectionDate(String value) {
        this.preferredInspectionDate = value;
    }

}
