//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.21 at 03:15:08 AM EAT 
//


package xmlparser.kensws.condoc1_v1_0;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the kenswscondoc1_v1_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: kenswscondoc1_v1_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ThirdPartyDetailsType }
     * 
     */
    public ThirdPartyDetailsType createThirdPartyDetailsType() {
        return new ThirdPartyDetailsType();
    }

    /**
     * Create an instance of {@link ContainerDetailsType }
     * 
     */
    public ContainerDetailsType createContainerDetailsType() {
        return new ContainerDetailsType();
    }

    /**
     * Create an instance of {@link SpareType }
     * 
     */
    public SpareType createSpareType() {
        return new SpareType();
    }

    /**
     * Create an instance of {@link UCRReferenceType }
     * 
     */
    public UCRReferenceType createUCRReferenceType() {
        return new UCRReferenceType();
    }

    /**
     * Create an instance of {@link ProductDetailsTwoType }
     * 
     */
    public ProductDetailsTwoType createProductDetailsTwoType() {
        return new ProductDetailsTwoType();
    }

    /**
     * Create an instance of {@link ItemAdditionalDetailsType }
     * 
     */
    public ItemAdditionalDetailsType createItemAdditionalDetailsType() {
        return new ItemAdditionalDetailsType();
    }

    /**
     * Create an instance of {@link TransportType }
     * 
     */
    public TransportType createTransportType() {
        return new TransportType();
    }

    /**
     * Create an instance of {@link HdrNonStandardDetailsType }
     * 
     */
    public HdrNonStandardDetailsType createHdrNonStandardDetailsType() {
        return new HdrNonStandardDetailsType();
    }

    /**
     * Create an instance of {@link EXIMCONType }
     * 
     */
    public EXIMCONType createEXIMCONType() {
        return new EXIMCONType();
    }

    /**
     * Create an instance of {@link DocumentIssueDateType }
     * 
     */
    public DocumentIssueDateType createDocumentIssueDateType() {
        return new DocumentIssueDateType();
    }

    /**
     * Create an instance of {@link TransportType2 }
     * 
     */
    public TransportType2 createTransportType2() {
        return new TransportType2();
    }

    /**
     * Create an instance of {@link DocumentIssueType }
     * 
     */
    public DocumentIssueType createDocumentIssueType() {
        return new DocumentIssueType();
    }

    /**
     * Create an instance of {@link ApprovalHistoryType }
     * 
     */
    public ApprovalHistoryType createApprovalHistoryType() {
        return new ApprovalHistoryType();
    }

    /**
     * Create an instance of {@link HdrAdditionalDetailsType }
     * 
     */
    public HdrAdditionalDetailsType createHdrAdditionalDetailsType() {
        return new HdrAdditionalDetailsType();
    }

    /**
     * Create an instance of {@link DocumentSummaryType }
     * 
     */
    public DocumentSummaryType createDocumentSummaryType() {
        return new DocumentSummaryType();
    }

    /**
     * Create an instance of {@link DocumentTypeDetails }
     * 
     */
    public DocumentTypeDetails createDocumentTypeDetails() {
        return new DocumentTypeDetails();
    }

    /**
     * Create an instance of {@link ProductDetailsOneType }
     * 
     */
    public ProductDetailsOneType createProductDetailsOneType() {
        return new ProductDetailsOneType();
    }

    /**
     * Create an instance of {@link EndUserDetailsType }
     * 
     */
    public EndUserDetailsType createEndUserDetailsType() {
        return new EndUserDetailsType();
    }

    /**
     * Create an instance of {@link NotifyPartyDetailsType }
     * 
     */
    public NotifyPartyDetailsType createNotifyPartyDetailsType() {
        return new NotifyPartyDetailsType();
    }

    /**
     * Create an instance of {@link HeaderTwoType }
     * 
     */
    public HeaderTwoType createHeaderTwoType() {
        return new HeaderTwoType();
    }

    /**
     * Create an instance of {@link DocumentExchangeDetailsType }
     * 
     */
    public DocumentExchangeDetailsType createDocumentExchangeDetailsType() {
        return new DocumentExchangeDetailsType();
    }

    /**
     * Create an instance of {@link StandardDetailsTwoType }
     * 
     */
    public StandardDetailsTwoType createStandardDetailsTwoType() {
        return new StandardDetailsTwoType();
    }

    /**
     * Create an instance of {@link AttachmentsType }
     * 
     */
    public AttachmentsType createAttachmentsType() {
        return new AttachmentsType();
    }

    /**
     * Create an instance of {@link ApprovalType }
     * 
     */
    public ApprovalType createApprovalType() {
        return new ApprovalType();
    }

    /**
     * Create an instance of {@link HeaderOneType }
     * 
     */
    public HeaderOneType createHeaderOneType() {
        return new HeaderOneType();
    }

    /**
     * Create an instance of {@link ReceivingPartyDetailsType }
     * 
     */
    public ReceivingPartyDetailsType createReceivingPartyDetailsType() {
        return new ReceivingPartyDetailsType();
    }

    /**
     * Create an instance of {@link EXIMDetailsType }
     * 
     */
    public EXIMDetailsType createEXIMDetailsType() {
        return new EXIMDetailsType();
    }

    /**
     * Create an instance of {@link QuantityType }
     * 
     */
    public QuantityType createQuantityType() {
        return new QuantityType();
    }

    /**
     * Create an instance of {@link DocumentHeaderType }
     * 
     */
    public DocumentHeaderType createDocumentHeaderType() {
        return new DocumentHeaderType();
    }

    /**
     * Create an instance of {@link ServiceProviderType }
     * 
     */
    public ServiceProviderType createServiceProviderType() {
        return new ServiceProviderType();
    }

    /**
     * Create an instance of {@link UCRNumberType }
     * 
     */
    public UCRNumberType createUCRNumberType() {
        return new UCRNumberType();
    }

    /**
     * Create an instance of {@link ItemNonStandardDetailsType }
     * 
     */
    public ItemNonStandardDetailsType createItemNonStandardDetailsType() {
        return new ItemNonStandardDetailsType();
    }

    /**
     * Create an instance of {@link FeeType }
     * 
     */
    public FeeType createFeeType() {
        return new FeeType();
    }

    /**
     * Create an instance of {@link DocumentReferenceType }
     * 
     */
    public DocumentReferenceType createDocumentReferenceType() {
        return new DocumentReferenceType();
    }

    /**
     * Create an instance of {@link StandardDetailsType }
     * 
     */
    public StandardDetailsType createStandardDetailsType() {
        return new StandardDetailsType();
    }

    /**
     * Create an instance of {@link ThirdPartyDetailsType.ThirdParties }
     * 
     */
    public ThirdPartyDetailsType.ThirdParties createThirdPartyDetailsTypeThirdParties() {
        return new ThirdPartyDetailsType.ThirdParties();
    }

    /**
     * Create an instance of {@link ContainerDetailsType.Containers }
     * 
     */
    public ContainerDetailsType.Containers createContainerDetailsTypeContainers() {
        return new ContainerDetailsType.Containers();
    }

}
