//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.21 at 03:24:53 AM EAT 
//


package xmlparser.kensws.condoc1_v1_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProductDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ItemDetails" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ItemCount" type="{MDA_Common_Types}ItemCountType"/>
 *                   &lt;element name="CDProduct1" type="{MDA_Common_Types}ProductDetailsOneType"/>
 *                   &lt;element name="CDProduct2" type="{MDA_Common_Types}ProductDetailsTwoType" minOccurs="0"/>
 *                   &lt;element name="CDItemNonStandard" type="{MDA_Common_Types}ItemNonStandardDetailsType" minOccurs="0"/>
 *                   &lt;element name="CDItemCommodity" type="{}ItemCommodityDetailsType" minOccurs="0"/>
 *                   &lt;element name="CDItemAdditional" type="{MDA_Common_Types}ItemAdditionalDetailsType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductDetailsType", namespace = "", propOrder = {
    "itemDetails"
})
public class ProductDetailsType {

    @XmlElement(name = "ItemDetails", required = true)
    protected List<ProductDetailsType.ItemDetails> itemDetails;

    /**
     * Gets the value of the itemDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductDetailsType.ItemDetails }
     * 
     * 
     */
    public List<ProductDetailsType.ItemDetails> getItemDetails() {
        if (itemDetails == null) {
            itemDetails = new ArrayList<ProductDetailsType.ItemDetails>();
        }
        return this.itemDetails;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ItemCount" type="{MDA_Common_Types}ItemCountType"/>
     *         &lt;element name="CDProduct1" type="{MDA_Common_Types}ProductDetailsOneType"/>
     *         &lt;element name="CDProduct2" type="{MDA_Common_Types}ProductDetailsTwoType" minOccurs="0"/>
     *         &lt;element name="CDItemNonStandard" type="{MDA_Common_Types}ItemNonStandardDetailsType" minOccurs="0"/>
     *         &lt;element name="CDItemCommodity" type="{}ItemCommodityDetailsType" minOccurs="0"/>
     *         &lt;element name="CDItemAdditional" type="{MDA_Common_Types}ItemAdditionalDetailsType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "itemCount",
        "cdProduct1",
        "cdProduct2",
        "cdItemNonStandard",
        "cdItemCommodity",
        "cdItemAdditional"
    })
    public static class ItemDetails {

        @XmlElement(name = "ItemCount", required = true)
        protected String itemCount;
        @XmlElement(name = "CDProduct1", required = true)
        protected ProductDetailsOneType cdProduct1;
        @XmlElement(name = "CDProduct2")
        protected ProductDetailsTwoType cdProduct2;
        @XmlElement(name = "CDItemNonStandard")
        protected ItemNonStandardDetailsType cdItemNonStandard;
        @XmlElement(name = "CDItemCommodity")
        protected ItemCommodityDetailsType cdItemCommodity;
        @XmlElement(name = "CDItemAdditional")
        protected ItemAdditionalDetailsType cdItemAdditional;

        /**
         * Gets the value of the itemCount property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getItemCount() {
            return itemCount;
        }

        /**
         * Sets the value of the itemCount property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItemCount(String value) {
            this.itemCount = value;
        }

        /**
         * Gets the value of the cdProduct1 property.
         * 
         * @return
         *     possible object is
         *     {@link ProductDetailsOneType }
         *     
         */
        public ProductDetailsOneType getCDProduct1() {
            return cdProduct1;
        }

        /**
         * Sets the value of the cdProduct1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link ProductDetailsOneType }
         *     
         */
        public void setCDProduct1(ProductDetailsOneType value) {
            this.cdProduct1 = value;
        }

        /**
         * Gets the value of the cdProduct2 property.
         * 
         * @return
         *     possible object is
         *     {@link ProductDetailsTwoType }
         *     
         */
        public ProductDetailsTwoType getCDProduct2() {
            return cdProduct2;
        }

        /**
         * Sets the value of the cdProduct2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link ProductDetailsTwoType }
         *     
         */
        public void setCDProduct2(ProductDetailsTwoType value) {
            this.cdProduct2 = value;
        }

        /**
         * Gets the value of the cdItemNonStandard property.
         * 
         * @return
         *     possible object is
         *     {@link ItemNonStandardDetailsType }
         *     
         */
        public ItemNonStandardDetailsType getCDItemNonStandard() {
            return cdItemNonStandard;
        }

        /**
         * Sets the value of the cdItemNonStandard property.
         * 
         * @param value
         *     allowed object is
         *     {@link ItemNonStandardDetailsType }
         *     
         */
        public void setCDItemNonStandard(ItemNonStandardDetailsType value) {
            this.cdItemNonStandard = value;
        }

        /**
         * Gets the value of the cdItemCommodity property.
         * 
         * @return
         *     possible object is
         *     {@link ItemCommodityDetailsType }
         *     
         */
        public ItemCommodityDetailsType getCDItemCommodity() {
            return cdItemCommodity;
        }

        /**
         * Sets the value of the cdItemCommodity property.
         * 
         * @param value
         *     allowed object is
         *     {@link ItemCommodityDetailsType }
         *     
         */
        public void setCDItemCommodity(ItemCommodityDetailsType value) {
            this.cdItemCommodity = value;
        }

        /**
         * Gets the value of the cdItemAdditional property.
         * 
         * @return
         *     possible object is
         *     {@link ItemAdditionalDetailsType }
         *     
         */
        public ItemAdditionalDetailsType getCDItemAdditional() {
            return cdItemAdditional;
        }

        /**
         * Sets the value of the cdItemAdditional property.
         * 
         * @param value
         *     allowed object is
         *     {@link ItemAdditionalDetailsType }
         *     
         */
        public void setCDItemAdditional(ItemAdditionalDetailsType value) {
            this.cdItemAdditional = value;
        }

    }

}
