//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.21 at 03:15:08 AM EAT 
//


package xmlparser.kensws.condoc1_v1_0;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProductDetailsOneType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductDetailsOneType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ItemNo" type="{MDA_Common_Types}ItemNoType"/>
 *         &lt;element name="ItemDescription" type="{MDA_Common_Types}ItemDescriptionType"/>
 *         &lt;element name="ItemHSCode" type="{MDA_Common_Types}HSCodeType"/>
 *         &lt;element name="HSDescription" type="{MDA_Common_Types}HSDescType"/>
 *         &lt;element name="InternalFileNumber" type="{MDA_Common_Types}InternalFileNumberType" minOccurs="0"/>
 *         &lt;element name="InternalProductNo" type="{MDA_Common_Types}InternalProductNoType" minOccurs="0"/>
 *         &lt;element name="ProductTechnicalName" type="{MDA_Common_Types}ProductTechnicalNameType" minOccurs="0"/>
 *         &lt;element name="ProductBrandName" type="{MDA_Common_Types}ProductBrandNameType" minOccurs="0"/>
 *         &lt;element name="ProductActiveIngredients" type="{MDA_Common_Types}ProductActiveIngredientsType" minOccurs="0"/>
 *         &lt;element name="ProductPackagingDetails" type="{MDA_Common_Types}ProductPackagingDetailsType" minOccurs="0"/>
 *         &lt;element name="ProductClassCode" type="{MDA_Common_Types}ProductClassCodeType" minOccurs="0"/>
 *         &lt;element name="ProductClassDescription" type="{MDA_Common_Types}ProductClassDescriptionType" minOccurs="0"/>
 *         &lt;element name="Quantity" type="{MDA_Common_Types}QuantityType"/>
 *         &lt;element name="SupplementryQuantity" type="{MDA_Common_Types}QuantityType" minOccurs="0"/>
 *         &lt;element name="PackageType" type="{MDA_Common_Types}PackType"/>
 *         &lt;element name="PackageTypeDesc" type="{MDA_Common_Types}PackTypeDesc" minOccurs="0"/>
 *         &lt;element name="PackageQty" type="{MDA_Common_Types}QTYType"/>
 *         &lt;element name="ForeignCurrencyCode" type="{MDA_Common_Types}CurrencyCodeType"/>
 *         &lt;element name="UnitPriceFCY" type="{MDA_Common_Types}FCYType"/>
 *         &lt;element name="TotalPriceFCY" type="{MDA_Common_Types}FCYType"/>
 *         &lt;element name="UnitPriceNCY" type="{MDA_Common_Types}NCYType"/>
 *         &lt;element name="CountryOfOrigin" type="{MDA_Common_Types}CountryType"/>
 *         &lt;element name="CountryOfOriginDesc" type="{MDA_Common_Types}CountryDescType2" minOccurs="0"/>
 *         &lt;element name="TotalPriceNCY" type="{MDA_Common_Types}NCYType" minOccurs="0"/>
 *         &lt;element name="ItemNetWeight" type="{MDA_Common_Types}WeightType"/>
 *         &lt;element name="ItemGrossWeight" type="{MDA_Common_Types}WeightType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductDetailsOneType", propOrder = {
    "itemNo",
    "itemDescription",
    "itemHSCode",
    "hsDescription",
    "internalFileNumber",
    "internalProductNo",
    "productTechnicalName",
    "productBrandName",
    "productActiveIngredients",
    "productPackagingDetails",
    "productClassCode",
    "productClassDescription",
    "quantity",
    "supplementryQuantity",
    "packageType",
    "packageTypeDesc",
    "packageQty",
    "foreignCurrencyCode",
    "unitPriceFCY",
    "totalPriceFCY",
    "unitPriceNCY",
    "countryOfOrigin",
    "countryOfOriginDesc",
    "totalPriceNCY",
    "itemNetWeight",
    "itemGrossWeight"
})
public class ProductDetailsOneType {

    @XmlElement(name = "ItemNo")
    protected int itemNo;
    @XmlElement(name = "ItemDescription", required = true)
    protected String itemDescription;
    @XmlElement(name = "ItemHSCode", required = true)
    protected String itemHSCode;
    @XmlElement(name = "HSDescription", required = true)
    protected String hsDescription;
    @XmlElement(name = "InternalFileNumber")
    protected String internalFileNumber;
    @XmlElement(name = "InternalProductNo")
    protected String internalProductNo;
    @XmlElement(name = "ProductTechnicalName")
    protected String productTechnicalName;
    @XmlElement(name = "ProductBrandName")
    protected String productBrandName;
    @XmlElement(name = "ProductActiveIngredients")
    protected String productActiveIngredients;
    @XmlElement(name = "ProductPackagingDetails")
    protected String productPackagingDetails;
    @XmlElement(name = "ProductClassCode")
    protected String productClassCode;
    @XmlElement(name = "ProductClassDescription")
    protected String productClassDescription;
    @XmlElement(name = "Quantity", required = true)
    protected QuantityType quantity;
    @XmlElement(name = "SupplementryQuantity")
    protected QuantityType supplementryQuantity;
    @XmlElement(name = "PackageType", required = true)
    protected String packageType;
    @XmlElement(name = "PackageTypeDesc")
    protected String packageTypeDesc;
    @XmlElement(name = "PackageQty", required = true)
    protected BigDecimal packageQty;
    @XmlElement(name = "ForeignCurrencyCode", required = true)
    protected String foreignCurrencyCode;
    @XmlElement(name = "UnitPriceFCY", required = true)
    protected BigDecimal unitPriceFCY;
    @XmlElement(name = "TotalPriceFCY", required = true)
    protected BigDecimal totalPriceFCY;
    @XmlElement(name = "UnitPriceNCY", required = true)
    protected BigDecimal unitPriceNCY;
    @XmlElement(name = "CountryOfOrigin", required = true)
    protected String countryOfOrigin;
    @XmlElement(name = "CountryOfOriginDesc")
    protected String countryOfOriginDesc;
    @XmlElement(name = "TotalPriceNCY")
    protected BigDecimal totalPriceNCY;
    @XmlElement(name = "ItemNetWeight", required = true)
    protected BigDecimal itemNetWeight;
    @XmlElement(name = "ItemGrossWeight", required = true)
    protected BigDecimal itemGrossWeight;

    /**
     * Gets the value of the itemNo property.
     * 
     */
    public int getItemNo() {
        return itemNo;
    }

    /**
     * Sets the value of the itemNo property.
     * 
     */
    public void setItemNo(int value) {
        this.itemNo = value;
    }

    /**
     * Gets the value of the itemDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemDescription() {
        return itemDescription;
    }

    /**
     * Sets the value of the itemDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemDescription(String value) {
        this.itemDescription = value;
    }

    /**
     * Gets the value of the itemHSCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemHSCode() {
        return itemHSCode;
    }

    /**
     * Sets the value of the itemHSCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemHSCode(String value) {
        this.itemHSCode = value;
    }

    /**
     * Gets the value of the hsDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHSDescription() {
        return hsDescription;
    }

    /**
     * Sets the value of the hsDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHSDescription(String value) {
        this.hsDescription = value;
    }

    /**
     * Gets the value of the internalFileNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternalFileNumber() {
        return internalFileNumber;
    }

    /**
     * Sets the value of the internalFileNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternalFileNumber(String value) {
        this.internalFileNumber = value;
    }

    /**
     * Gets the value of the internalProductNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternalProductNo() {
        return internalProductNo;
    }

    /**
     * Sets the value of the internalProductNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternalProductNo(String value) {
        this.internalProductNo = value;
    }

    /**
     * Gets the value of the productTechnicalName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductTechnicalName() {
        return productTechnicalName;
    }

    /**
     * Sets the value of the productTechnicalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductTechnicalName(String value) {
        this.productTechnicalName = value;
    }

    /**
     * Gets the value of the productBrandName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductBrandName() {
        return productBrandName;
    }

    /**
     * Sets the value of the productBrandName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductBrandName(String value) {
        this.productBrandName = value;
    }

    /**
     * Gets the value of the productActiveIngredients property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductActiveIngredients() {
        return productActiveIngredients;
    }

    /**
     * Sets the value of the productActiveIngredients property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductActiveIngredients(String value) {
        this.productActiveIngredients = value;
    }

    /**
     * Gets the value of the productPackagingDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductPackagingDetails() {
        return productPackagingDetails;
    }

    /**
     * Sets the value of the productPackagingDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductPackagingDetails(String value) {
        this.productPackagingDetails = value;
    }

    /**
     * Gets the value of the productClassCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductClassCode() {
        return productClassCode;
    }

    /**
     * Sets the value of the productClassCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductClassCode(String value) {
        this.productClassCode = value;
    }

    /**
     * Gets the value of the productClassDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductClassDescription() {
        return productClassDescription;
    }

    /**
     * Sets the value of the productClassDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductClassDescription(String value) {
        this.productClassDescription = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link QuantityType }
     *     
     */
    public QuantityType getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantityType }
     *     
     */
    public void setQuantity(QuantityType value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the supplementryQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link QuantityType }
     *     
     */
    public QuantityType getSupplementryQuantity() {
        return supplementryQuantity;
    }

    /**
     * Sets the value of the supplementryQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantityType }
     *     
     */
    public void setSupplementryQuantity(QuantityType value) {
        this.supplementryQuantity = value;
    }

    /**
     * Gets the value of the packageType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackageType() {
        return packageType;
    }

    /**
     * Sets the value of the packageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackageType(String value) {
        this.packageType = value;
    }

    /**
     * Gets the value of the packageTypeDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackageTypeDesc() {
        return packageTypeDesc;
    }

    /**
     * Sets the value of the packageTypeDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackageTypeDesc(String value) {
        this.packageTypeDesc = value;
    }

    /**
     * Gets the value of the packageQty property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPackageQty() {
        return packageQty;
    }

    /**
     * Sets the value of the packageQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPackageQty(BigDecimal value) {
        this.packageQty = value;
    }

    /**
     * Gets the value of the foreignCurrencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForeignCurrencyCode() {
        return foreignCurrencyCode;
    }

    /**
     * Sets the value of the foreignCurrencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForeignCurrencyCode(String value) {
        this.foreignCurrencyCode = value;
    }

    /**
     * Gets the value of the unitPriceFCY property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUnitPriceFCY() {
        return unitPriceFCY;
    }

    /**
     * Sets the value of the unitPriceFCY property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUnitPriceFCY(BigDecimal value) {
        this.unitPriceFCY = value;
    }

    /**
     * Gets the value of the totalPriceFCY property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalPriceFCY() {
        return totalPriceFCY;
    }

    /**
     * Sets the value of the totalPriceFCY property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalPriceFCY(BigDecimal value) {
        this.totalPriceFCY = value;
    }

    /**
     * Gets the value of the unitPriceNCY property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUnitPriceNCY() {
        return unitPriceNCY;
    }

    /**
     * Sets the value of the unitPriceNCY property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUnitPriceNCY(BigDecimal value) {
        this.unitPriceNCY = value;
    }

    /**
     * Gets the value of the countryOfOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryOfOrigin() {
        return countryOfOrigin;
    }

    /**
     * Sets the value of the countryOfOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryOfOrigin(String value) {
        this.countryOfOrigin = value;
    }

    /**
     * Gets the value of the countryOfOriginDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryOfOriginDesc() {
        return countryOfOriginDesc;
    }

    /**
     * Sets the value of the countryOfOriginDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryOfOriginDesc(String value) {
        this.countryOfOriginDesc = value;
    }

    /**
     * Gets the value of the totalPriceNCY property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalPriceNCY() {
        return totalPriceNCY;
    }

    /**
     * Sets the value of the totalPriceNCY property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalPriceNCY(BigDecimal value) {
        this.totalPriceNCY = value;
    }

    /**
     * Gets the value of the itemNetWeight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getItemNetWeight() {
        return itemNetWeight;
    }

    /**
     * Sets the value of the itemNetWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setItemNetWeight(BigDecimal value) {
        this.itemNetWeight = value;
    }

    /**
     * Gets the value of the itemGrossWeight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getItemGrossWeight() {
        return itemGrossWeight;
    }

    /**
     * Sets the value of the itemGrossWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setItemGrossWeight(BigDecimal value) {
        this.itemGrossWeight = value;
    }

}
