//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.21 at 03:15:08 AM EAT 
//


package xmlparser.kensws.condoc1_v1_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StandardDetailsTwoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StandardDetailsTwoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ConditionsOfApproval" type="{MDA_Common_Types}ConditionsOfApprovalType" minOccurs="0"/>
 *         &lt;element name="ApplicantRemarks" type="{MDA_Common_Types}RemarksType" minOccurs="0"/>
 *         &lt;element name="MDARemarks" type="{MDA_Common_Types}RemarksType" minOccurs="0"/>
 *         &lt;element name="CustomsRemarks" type="{MDA_Common_Types}RemarksType" minOccurs="0"/>
 *         &lt;element name="PurposeOfImport" type="{MDA_Common_Types}PurposeOfImportType"/>
 *         &lt;element name="ThirdPartyDetails" type="{MDA_Common_Types}ThirdPartyDetailsType" minOccurs="0"/>
 *         &lt;element name="ApplicantDefinedThirdPartyDetails" type="{MDA_Common_Types}ThirdPartyDetailsType" minOccurs="0"/>
 *         &lt;element name="ProcessingFee" type="{MDA_Common_Types}FeeType" minOccurs="0"/>
 *         &lt;element name="DocumentFee" type="{MDA_Common_Types}FeeType" minOccurs="0"/>
 *         &lt;element name="Attachments" type="{MDA_Common_Types}AttachmentsType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StandardDetailsTwoType", propOrder = {
    "conditionsOfApproval",
    "applicantRemarks",
    "mdaRemarks",
    "customsRemarks",
    "purposeOfImport",
    "thirdPartyDetails",
    "applicantDefinedThirdPartyDetails",
    "processingFee",
    "documentFee",
    "attachments"
})
public class StandardDetailsTwoType {

    @XmlElement(name = "ConditionsOfApproval")
    protected String conditionsOfApproval;
    @XmlElement(name = "ApplicantRemarks")
    protected String applicantRemarks;
    @XmlElement(name = "MDARemarks")
    protected String mdaRemarks;
    @XmlElement(name = "CustomsRemarks")
    protected String customsRemarks;
    @XmlElement(name = "PurposeOfImport", required = true)
    protected String purposeOfImport;
    @XmlElement(name = "ThirdPartyDetails")
    protected ThirdPartyDetailsType thirdPartyDetails;
    @XmlElement(name = "ApplicantDefinedThirdPartyDetails")
    protected ThirdPartyDetailsType applicantDefinedThirdPartyDetails;
    @XmlElement(name = "ProcessingFee")
    protected FeeType processingFee;
    @XmlElement(name = "DocumentFee")
    protected FeeType documentFee;
    @XmlElement(name = "Attachments")
    protected List<AttachmentsType> attachments;

    /**
     * Gets the value of the conditionsOfApproval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConditionsOfApproval() {
        return conditionsOfApproval;
    }

    /**
     * Sets the value of the conditionsOfApproval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConditionsOfApproval(String value) {
        this.conditionsOfApproval = value;
    }

    /**
     * Gets the value of the applicantRemarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicantRemarks() {
        return applicantRemarks;
    }

    /**
     * Sets the value of the applicantRemarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicantRemarks(String value) {
        this.applicantRemarks = value;
    }

    /**
     * Gets the value of the mdaRemarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMDARemarks() {
        return mdaRemarks;
    }

    /**
     * Sets the value of the mdaRemarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMDARemarks(String value) {
        this.mdaRemarks = value;
    }

    /**
     * Gets the value of the customsRemarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomsRemarks() {
        return customsRemarks;
    }

    /**
     * Sets the value of the customsRemarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomsRemarks(String value) {
        this.customsRemarks = value;
    }

    /**
     * Gets the value of the purposeOfImport property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurposeOfImport() {
        return purposeOfImport;
    }

    /**
     * Sets the value of the purposeOfImport property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurposeOfImport(String value) {
        this.purposeOfImport = value;
    }

    /**
     * Gets the value of the thirdPartyDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ThirdPartyDetailsType }
     *     
     */
    public ThirdPartyDetailsType getThirdPartyDetails() {
        return thirdPartyDetails;
    }

    /**
     * Sets the value of the thirdPartyDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ThirdPartyDetailsType }
     *     
     */
    public void setThirdPartyDetails(ThirdPartyDetailsType value) {
        this.thirdPartyDetails = value;
    }

    /**
     * Gets the value of the applicantDefinedThirdPartyDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ThirdPartyDetailsType }
     *     
     */
    public ThirdPartyDetailsType getApplicantDefinedThirdPartyDetails() {
        return applicantDefinedThirdPartyDetails;
    }

    /**
     * Sets the value of the applicantDefinedThirdPartyDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ThirdPartyDetailsType }
     *     
     */
    public void setApplicantDefinedThirdPartyDetails(ThirdPartyDetailsType value) {
        this.applicantDefinedThirdPartyDetails = value;
    }

    /**
     * Gets the value of the processingFee property.
     * 
     * @return
     *     possible object is
     *     {@link FeeType }
     *     
     */
    public FeeType getProcessingFee() {
        return processingFee;
    }

    /**
     * Sets the value of the processingFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeeType }
     *     
     */
    public void setProcessingFee(FeeType value) {
        this.processingFee = value;
    }

    /**
     * Gets the value of the documentFee property.
     * 
     * @return
     *     possible object is
     *     {@link FeeType }
     *     
     */
    public FeeType getDocumentFee() {
        return documentFee;
    }

    /**
     * Sets the value of the documentFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeeType }
     *     
     */
    public void setDocumentFee(FeeType value) {
        this.documentFee = value;
    }

    /**
     * Gets the value of the attachments property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attachments property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttachments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AttachmentsType }
     * 
     * 
     */
    public List<AttachmentsType> getAttachments() {
        if (attachments == null) {
            attachments = new ArrayList<AttachmentsType>();
        }
        return this.attachments;
    }

}
