//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.21 at 03:15:08 AM EAT 
//


package xmlparser.kensws.condoc1_v1_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ThirdPartyDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ThirdPartyDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ThirdParties" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ThirdPartyCode" type="{MDA_Common_Types}ThirdPartyCodeType" minOccurs="0"/>
 *                   &lt;element name="ThirdPartyDescription" type="{MDA_Common_Types}ThirdPartyDescriptionType" minOccurs="0"/>
 *                   &lt;element name="DistributionMethod" type="{MDA_Common_Types}DistributionMethodType" minOccurs="0"/>
 *                   &lt;element name="ThirdPartyMailbox" type="{MDA_Common_Types}ThirdPartyMailboxType" minOccurs="0"/>
 *                   &lt;element name="ThirdPartyAccount" type="{MDA_Common_Types}ThirdPartyAccountType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ThirdPartyDetailsType", propOrder = {
    "thirdParties"
})
public class ThirdPartyDetailsType {

    @XmlElement(name = "ThirdParties", required = true)
    protected List<ThirdPartyDetailsType.ThirdParties> thirdParties;

    /**
     * Gets the value of the thirdParties property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the thirdParties property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getThirdParties().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ThirdPartyDetailsType.ThirdParties }
     * 
     * 
     */
    public List<ThirdPartyDetailsType.ThirdParties> getThirdParties() {
        if (thirdParties == null) {
            thirdParties = new ArrayList<ThirdPartyDetailsType.ThirdParties>();
        }
        return this.thirdParties;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ThirdPartyCode" type="{MDA_Common_Types}ThirdPartyCodeType" minOccurs="0"/>
     *         &lt;element name="ThirdPartyDescription" type="{MDA_Common_Types}ThirdPartyDescriptionType" minOccurs="0"/>
     *         &lt;element name="DistributionMethod" type="{MDA_Common_Types}DistributionMethodType" minOccurs="0"/>
     *         &lt;element name="ThirdPartyMailbox" type="{MDA_Common_Types}ThirdPartyMailboxType" minOccurs="0"/>
     *         &lt;element name="ThirdPartyAccount" type="{MDA_Common_Types}ThirdPartyAccountType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "thirdPartyCode",
        "thirdPartyDescription",
        "distributionMethod",
        "thirdPartyMailbox",
        "thirdPartyAccount"
    })
    public static class ThirdParties {

        @XmlElement(name = "ThirdPartyCode")
        protected String thirdPartyCode;
        @XmlElement(name = "ThirdPartyDescription")
        protected String thirdPartyDescription;
        @XmlElement(name = "DistributionMethod")
        protected String distributionMethod;
        @XmlElement(name = "ThirdPartyMailbox")
        protected String thirdPartyMailbox;
        @XmlElement(name = "ThirdPartyAccount")
        protected String thirdPartyAccount;

        /**
         * Gets the value of the thirdPartyCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getThirdPartyCode() {
            return thirdPartyCode;
        }

        /**
         * Sets the value of the thirdPartyCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setThirdPartyCode(String value) {
            this.thirdPartyCode = value;
        }

        /**
         * Gets the value of the thirdPartyDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getThirdPartyDescription() {
            return thirdPartyDescription;
        }

        /**
         * Sets the value of the thirdPartyDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setThirdPartyDescription(String value) {
            this.thirdPartyDescription = value;
        }

        /**
         * Gets the value of the distributionMethod property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDistributionMethod() {
            return distributionMethod;
        }

        /**
         * Sets the value of the distributionMethod property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDistributionMethod(String value) {
            this.distributionMethod = value;
        }

        /**
         * Gets the value of the thirdPartyMailbox property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getThirdPartyMailbox() {
            return thirdPartyMailbox;
        }

        /**
         * Sets the value of the thirdPartyMailbox property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setThirdPartyMailbox(String value) {
            this.thirdPartyMailbox = value;
        }

        /**
         * Gets the value of the thirdPartyAccount property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getThirdPartyAccount() {
            return thirdPartyAccount;
        }

        /**
         * Sets the value of the thirdPartyAccount property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setThirdPartyAccount(String value) {
            this.thirdPartyAccount = value;
        }

    }

}
