//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.21 at 03:15:08 AM EAT 
//


package xmlparser.kensws.condoc1_v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransportType2 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransportType2">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TransportCode" type="{MDA_Common_Types}TransportCodeType" minOccurs="0"/>
 *         &lt;element name="TransportCodeDesc" type="{MDA_Common_Types}TransportCodeDescType" minOccurs="0"/>
 *         &lt;element name="TransportReason" type="{MDA_Common_Types}TransportReasonType"/>
 *         &lt;element name="TransportResponsiblity" type="{MDA_Common_Types}TransportResponsiblityType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransportType2", propOrder = {
    "transportCode",
    "transportCodeDesc",
    "transportReason",
    "transportResponsiblity"
})
public class TransportType2 {

    @XmlElement(name = "TransportCode")
    protected String transportCode;
    @XmlElement(name = "TransportCodeDesc")
    protected String transportCodeDesc;
    @XmlElement(name = "TransportReason", required = true)
    protected String transportReason;
    @XmlElement(name = "TransportResponsiblity", required = true)
    protected String transportResponsiblity;

    /**
     * Gets the value of the transportCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransportCode() {
        return transportCode;
    }

    /**
     * Sets the value of the transportCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransportCode(String value) {
        this.transportCode = value;
    }

    /**
     * Gets the value of the transportCodeDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransportCodeDesc() {
        return transportCodeDesc;
    }

    /**
     * Sets the value of the transportCodeDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransportCodeDesc(String value) {
        this.transportCodeDesc = value;
    }

    /**
     * Gets the value of the transportReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransportReason() {
        return transportReason;
    }

    /**
     * Sets the value of the transportReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransportReason(String value) {
        this.transportReason = value;
    }

    /**
     * Gets the value of the transportResponsiblity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransportResponsiblity() {
        return transportResponsiblity;
    }

    /**
     * Sets the value of the transportResponsiblity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransportResponsiblity(String value) {
        this.transportResponsiblity = value;
    }

}
