//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.21 at 03:15:08 AM EAT 
//


package xmlparser.kensws.condoc1_v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UCRNumberType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UCRNumberType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UCRNo" type="{MDA_Common_Types}UCRNoType"/>
 *         &lt;element name="MessageDateTime" type="{MDA_Common_Types}MessageDateTimeType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UCRNumberType", propOrder = {
    "ucrNo",
    "messageDateTime"
})
public class UCRNumberType {

    @XmlElement(name = "UCRNo", required = true)
    protected String ucrNo;
    @XmlElement(name = "MessageDateTime", required = true)
    protected String messageDateTime;

    /**
     * Gets the value of the ucrNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUCRNo() {
        return ucrNo;
    }

    /**
     * Sets the value of the ucrNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCRNo(String value) {
        this.ucrNo = value;
    }

    /**
     * Gets the value of the messageDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageDateTime() {
        return messageDateTime;
    }

    /**
     * Sets the value of the messageDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageDateTime(String value) {
        this.messageDateTime = value;
    }

}
