//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.21 at 03:48:15 AM EAT 
//


package xmlparser.kensws.og_cd_res_v1_0;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for DocumentDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DocumentDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="consignment_refnumber" type="{}ApplnRefNoType"/>
 *         &lt;element name="ver_no" type="{}VersionNoType"/>
 *         &lt;element name="certificate_no" type="{}PermitNoType" minOccurs="0"/>
 *         &lt;element name="permit_no" type="{}PermitNoType" minOccurs="0"/>
 *         &lt;element name="status" type="{}StatusCodeType"/>
 *         &lt;element name="role_code" type="{}RoleCodeType"/>
 *         &lt;element name="vo_ind" type="{}IndicatorType" minOccurs="0"/>
 *         &lt;element name="io_ind" type="{}IndicatorType" minOccurs="0"/>
 *         &lt;element name="inspection_type" type="{}InspectionType" minOccurs="0"/>
 *         &lt;element name="cont_details" type="{}ContainerType" minOccurs="0"/>
 *         &lt;element name="user_id" type="{}UserIdType"/>
 *         &lt;element name="pga_remarks" type="{}RemarksType"/>
 *         &lt;element name="conditional_remarks" type="{}RemarksType" minOccurs="0"/>
 *         &lt;element name="oga_queries" type="{}RemarksType" minOccurs="0"/>
 *         &lt;element name="queries_response" type="{}RemarksType" minOccurs="0"/>
 *         &lt;element name="amount" type="{}AmountType"/>
 *         &lt;element name="currency" type="{}CurrencyType" minOccurs="0"/>
 *         &lt;element name="revenue_code" type="{}RevenueCodeType" minOccurs="0"/>
 *         &lt;element name="expiry_date" type="{}TimeStampType" minOccurs="0"/>
 *         &lt;element name="pga_risk_assessment_lane" type="{}RiskAssLaneType" minOccurs="0"/>
 *         &lt;element name="assessed_by" type="{}UserIdType" minOccurs="0"/>
 *         &lt;element name="assessed_date" type="{}TimeStampType" minOccurs="0"/>
 *         &lt;element name="assessed_remarks" type="{}RemarksType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DocumentDetailsType", propOrder = {
    "consignmentRefnumber",
    "verNo",
    "certificateNo",
    "permitNo",
    "status",
    "roleCode",
    "voInd",
    "ioInd",
    "inspectionType",
    "contDetails",
    "userId",
    "pgaRemarks",
    "conditionalRemarks",
    "ogaQueries",
    "queriesResponse",
    "amount",
    "currency",
    "revenueCode",
    "expiryDate",
    "pgaRiskAssessmentLane",
    "assessedBy",
    "assessedDate",
    "assessedRemarks"
})
public class DocumentDetailsType {

    @XmlElement(name = "consignment_refnumber", required = true)
    protected String consignmentRefnumber;
    @XmlElement(name = "ver_no", required = true)
    protected String verNo;
    @XmlElement(name = "certificate_no")
    protected String certificateNo;
    @XmlElement(name = "permit_no")
    protected String permitNo;
    @XmlElement(required = true)
    protected String status;
    @XmlElement(name = "role_code", required = true)
    protected String roleCode;
    @XmlElement(name = "vo_ind")
    protected String voInd;
    @XmlElement(name = "io_ind")
    protected String ioInd;
    @XmlElement(name = "inspection_type")
    protected String inspectionType;
    @XmlElement(name = "cont_details")
    protected ContainerType contDetails;
    @XmlElement(name = "user_id", required = true)
    protected String userId;
    @XmlElement(name = "pga_remarks", required = true)
    protected String pgaRemarks;
    @XmlElement(name = "conditional_remarks")
    protected String conditionalRemarks;
    @XmlElement(name = "oga_queries")
    protected String ogaQueries;
    @XmlElement(name = "queries_response")
    protected String queriesResponse;
    @XmlElement(required = true)
    protected BigDecimal amount;
    protected String currency;
    @XmlElement(name = "revenue_code")
    protected String revenueCode;
    @XmlElement(name = "expiry_date")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String expiryDate;
    @XmlElement(name = "pga_risk_assessment_lane")
    protected String pgaRiskAssessmentLane;
    @XmlElement(name = "assessed_by")
    protected String assessedBy;
    @XmlElement(name = "assessed_date")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String assessedDate;
    @XmlElement(name = "assessed_remarks")
    protected String assessedRemarks;

    /**
     * Gets the value of the consignmentRefnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsignmentRefnumber() {
        return consignmentRefnumber;
    }

    /**
     * Sets the value of the consignmentRefnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsignmentRefnumber(String value) {
        this.consignmentRefnumber = value;
    }

    /**
     * Gets the value of the verNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerNo() {
        return verNo;
    }

    /**
     * Sets the value of the verNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerNo(String value) {
        this.verNo = value;
    }

    /**
     * Gets the value of the certificateNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertificateNo() {
        return certificateNo;
    }

    /**
     * Sets the value of the certificateNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertificateNo(String value) {
        this.certificateNo = value;
    }

    /**
     * Gets the value of the permitNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPermitNo() {
        return permitNo;
    }

    /**
     * Sets the value of the permitNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPermitNo(String value) {
        this.permitNo = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the roleCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * Sets the value of the roleCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoleCode(String value) {
        this.roleCode = value;
    }

    /**
     * Gets the value of the voInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoInd() {
        return voInd;
    }

    /**
     * Sets the value of the voInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoInd(String value) {
        this.voInd = value;
    }

    /**
     * Gets the value of the ioInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIoInd() {
        return ioInd;
    }

    /**
     * Sets the value of the ioInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIoInd(String value) {
        this.ioInd = value;
    }

    /**
     * Gets the value of the inspectionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInspectionType() {
        return inspectionType;
    }

    /**
     * Sets the value of the inspectionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInspectionType(String value) {
        this.inspectionType = value;
    }

    /**
     * Gets the value of the contDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ContainerType }
     *     
     */
    public ContainerType getContDetails() {
        return contDetails;
    }

    /**
     * Sets the value of the contDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContainerType }
     *     
     */
    public void setContDetails(ContainerType value) {
        this.contDetails = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserId(String value) {
        this.userId = value;
    }

    /**
     * Gets the value of the pgaRemarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPgaRemarks() {
        return pgaRemarks;
    }

    /**
     * Sets the value of the pgaRemarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPgaRemarks(String value) {
        this.pgaRemarks = value;
    }

    /**
     * Gets the value of the conditionalRemarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConditionalRemarks() {
        return conditionalRemarks;
    }

    /**
     * Sets the value of the conditionalRemarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConditionalRemarks(String value) {
        this.conditionalRemarks = value;
    }

    /**
     * Gets the value of the ogaQueries property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOgaQueries() {
        return ogaQueries;
    }

    /**
     * Sets the value of the ogaQueries property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOgaQueries(String value) {
        this.ogaQueries = value;
    }

    /**
     * Gets the value of the queriesResponse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQueriesResponse() {
        return queriesResponse;
    }

    /**
     * Sets the value of the queriesResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQueriesResponse(String value) {
        this.queriesResponse = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmount(BigDecimal value) {
        this.amount = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the revenueCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevenueCode() {
        return revenueCode;
    }

    /**
     * Sets the value of the revenueCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevenueCode(String value) {
        this.revenueCode = value;
    }

    /**
     * Gets the value of the expiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpiryDate() {
        return expiryDate;
    }

    /**
     * Sets the value of the expiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpiryDate(String value) {
        this.expiryDate = value;
    }

    /**
     * Gets the value of the pgaRiskAssessmentLane property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPgaRiskAssessmentLane() {
        return pgaRiskAssessmentLane;
    }

    /**
     * Sets the value of the pgaRiskAssessmentLane property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPgaRiskAssessmentLane(String value) {
        this.pgaRiskAssessmentLane = value;
    }

    /**
     * Gets the value of the assessedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssessedBy() {
        return assessedBy;
    }

    /**
     * Sets the value of the assessedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssessedBy(String value) {
        this.assessedBy = value;
    }

    /**
     * Gets the value of the assessedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssessedDate() {
        return assessedDate;
    }

    /**
     * Sets the value of the assessedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssessedDate(String value) {
        this.assessedDate = value;
    }

    /**
     * Gets the value of the assessedRemarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssessedRemarks() {
        return assessedRemarks;
    }

    /**
     * Sets the value of the assessedRemarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssessedRemarks(String value) {
        this.assessedRemarks = value;
    }

}
