//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.21 at 03:48:15 AM EAT 
//


package xmlparser.kensws.og_cd_res_v1_0;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for DocumentHeaderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DocumentHeaderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="msgid" type="{}MessageIdentifierType"/>
 *         &lt;element name="refno" type="{}ReferenceNumberType"/>
 *         &lt;element name="msg_func" type="{}MsgFuncType"/>
 *         &lt;element name="sender" type="{}SenderReceiverType"/>
 *         &lt;element name="receiver" type="{}SenderReceiverType"/>
 *         &lt;element name="version" type="{}VersionNoType"/>
 *         &lt;element name="docno" type="{}DocumentNumberType" minOccurs="0"/>
 *         &lt;element name="docgroup" type="{}DocumentGroupType" minOccurs="0"/>
 *         &lt;element name="msgdate" type="{}TimeStampType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DocumentHeaderType", propOrder = {
    "msgid",
    "refno",
    "msgFunc",
    "sender",
    "receiver",
    "version",
    "docno",
    "docgroup",
    "msgdate"
})
public class DocumentHeaderType {

    @XmlElement(required = true)
    protected String msgid;
    @XmlElement(required = true)
    protected String refno;
    @XmlElement(name = "msg_func", required = true)
    protected BigInteger msgFunc;
    @XmlElement(required = true)
    protected String sender;
    @XmlElement(required = true)
    protected String receiver;
    @XmlElement(required = true)
    protected String version;
    protected String docno;
    protected String docgroup;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String msgdate;

    /**
     * Gets the value of the msgid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgid() {
        return msgid;
    }

    /**
     * Sets the value of the msgid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgid(String value) {
        this.msgid = value;
    }

    /**
     * Gets the value of the refno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefno() {
        return refno;
    }

    /**
     * Sets the value of the refno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefno(String value) {
        this.refno = value;
    }

    /**
     * Gets the value of the msgFunc property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMsgFunc() {
        return msgFunc;
    }

    /**
     * Sets the value of the msgFunc property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMsgFunc(BigInteger value) {
        this.msgFunc = value;
    }

    /**
     * Gets the value of the sender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSender() {
        return sender;
    }

    /**
     * Sets the value of the sender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSender(String value) {
        this.sender = value;
    }

    /**
     * Gets the value of the receiver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * Sets the value of the receiver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiver(String value) {
        this.receiver = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the docno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocno() {
        return docno;
    }

    /**
     * Sets the value of the docno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocno(String value) {
        this.docno = value;
    }

    /**
     * Gets the value of the docgroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocgroup() {
        return docgroup;
    }

    /**
     * Sets the value of the docgroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocgroup(String value) {
        this.docgroup = value;
    }

    /**
     * Gets the value of the msgdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgdate() {
        return msgdate;
    }

    /**
     * Sets the value of the msgdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgdate(String value) {
        this.msgdate = value;
    }

}
