package databaselayer.ecs_kesws.entities;
// Generated Oct 29, 2014 3:56:07 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CdFileDetails generated by hbm2java
 */
@Entity
@Table(name="CD_FILE_DETAILS"
    ,catalog="ECS_KESWS"
)
public class CdFileDetails  implements java.io.Serializable {


     private int id;
     private EcsDocumentTypes ecsDocumentTypes;
     private PricelistInternalProductcodeDocumentMap pricelistInternalProductcodeDocumentMap;
     private RecCdFileMsg recCdFileMsg;
     private Double weight;
     private String ipcIdCode;

    public CdFileDetails() {
    }

	
    public CdFileDetails(int id, EcsDocumentTypes ecsDocumentTypes, PricelistInternalProductcodeDocumentMap pricelistInternalProductcodeDocumentMap, RecCdFileMsg recCdFileMsg) {
        this.id = id;
        this.ecsDocumentTypes = ecsDocumentTypes;
        this.pricelistInternalProductcodeDocumentMap = pricelistInternalProductcodeDocumentMap;
        this.recCdFileMsg = recCdFileMsg;
    }
    public CdFileDetails(int id, EcsDocumentTypes ecsDocumentTypes, PricelistInternalProductcodeDocumentMap pricelistInternalProductcodeDocumentMap, RecCdFileMsg recCdFileMsg, Double weight, String ipcIdCode) {
       this.id = id;
       this.ecsDocumentTypes = ecsDocumentTypes;
       this.pricelistInternalProductcodeDocumentMap = pricelistInternalProductcodeDocumentMap;
       this.recCdFileMsg = recCdFileMsg;
       this.weight = weight;
       this.ipcIdCode = ipcIdCode;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DOCUMENT_TYPES_id_Ref", nullable=false)
    public EcsDocumentTypes getEcsDocumentTypes() {
        return this.ecsDocumentTypes;
    }
    
    public void setEcsDocumentTypes(EcsDocumentTypes ecsDocumentTypes) {
        this.ecsDocumentTypes = ecsDocumentTypes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PRICE_LIST_INT_IPC_DOCUMENT_MAP_Pricelist_IPC_MAP_ID_Ref", nullable=false)
    public PricelistInternalProductcodeDocumentMap getPricelistInternalProductcodeDocumentMap() {
        return this.pricelistInternalProductcodeDocumentMap;
    }
    
    public void setPricelistInternalProductcodeDocumentMap(PricelistInternalProductcodeDocumentMap pricelistInternalProductcodeDocumentMap) {
        this.pricelistInternalProductcodeDocumentMap = pricelistInternalProductcodeDocumentMap;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="REC_CD_FILE_MSG_REC_CD_FILE_ID_Ref", nullable=false)
    public RecCdFileMsg getRecCdFileMsg() {
        return this.recCdFileMsg;
    }
    
    public void setRecCdFileMsg(RecCdFileMsg recCdFileMsg) {
        this.recCdFileMsg = recCdFileMsg;
    }

    
    @Column(name="Weight", precision=22, scale=0)
    public Double getWeight() {
        return this.weight;
    }
    
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    
    @Column(name="IPC_ID_CODE")
    public String getIpcIdCode() {
        return this.ipcIdCode;
    }
    
    public void setIpcIdCode(String ipcIdCode) {
        this.ipcIdCode = ipcIdCode;
    }




}


