package databaselayer.ecs_kesws.entities;
// Generated Oct 29, 2014 3:56:07 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EcsResCdFileMsg generated by hbm2java
 */
@Entity
@Table(name="ECS_RES_CD_FILE_MSG"
    ,catalog="ECS_KESWS"
)
public class EcsResCdFileMsg  implements java.io.Serializable {


     private Integer ecsResCdFileMsgId;
     private String ecsResCdFileMsgUcrNo;
     private Set<RecErrorMsg> recErrorMsgs = new HashSet<RecErrorMsg>(0);

    public EcsResCdFileMsg() {
    }

    public EcsResCdFileMsg(String ecsResCdFileMsgUcrNo, Set<RecErrorMsg> recErrorMsgs) {
       this.ecsResCdFileMsgUcrNo = ecsResCdFileMsgUcrNo;
       this.recErrorMsgs = recErrorMsgs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ECS_RES_CD_FILE_MSG_ID", unique=true, nullable=false)
    public Integer getEcsResCdFileMsgId() {
        return this.ecsResCdFileMsgId;
    }
    
    public void setEcsResCdFileMsgId(Integer ecsResCdFileMsgId) {
        this.ecsResCdFileMsgId = ecsResCdFileMsgId;
    }

    
    @Column(name="ECS_RES_CD_FILE_MSG_UCR_NO")
    public String getEcsResCdFileMsgUcrNo() {
        return this.ecsResCdFileMsgUcrNo;
    }
    
    public void setEcsResCdFileMsgUcrNo(String ecsResCdFileMsgUcrNo) {
        this.ecsResCdFileMsgUcrNo = ecsResCdFileMsgUcrNo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ecsResCdFileMsg")
    public Set<RecErrorMsg> getRecErrorMsgs() {
        return this.recErrorMsgs;
    }
    
    public void setRecErrorMsgs(Set<RecErrorMsg> recErrorMsgs) {
        this.recErrorMsgs = recErrorMsgs;
    }




}


