package databaselayer.ecs_kesws.entities;
// Generated Oct 29, 2014 3:56:07 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * InternalProductcodes generated by hbm2java
 */
@Entity
@Table(name="INTERNAL_PRODUCTCODES"
    ,catalog="ECS_KESWS"
    , uniqueConstraints = @UniqueConstraint(columnNames={"Internal_Product_Code", "HSCODE"}) 
)
public class InternalProductcodes  implements java.io.Serializable {


     private Integer ipcId;
     private String hscode;
     private String internalProductCode;
     private String hscodeDesc;
     private String commodityCategory;
     private String commodityType;
     private String commodityTechnicalName;
     private String commodityVariety;
     private String commodityForm;
     private Integer priceListIpcMapIdRef;
     private Integer isActiveIpc;
     private Date dateCreated;
     private Date dateDeactivated;
     private Set<PricelistInternalProductcodeDocumentMap> pricelistInternalProductcodeDocumentMaps = new HashSet<PricelistInternalProductcodeDocumentMap>(0);

    public InternalProductcodes() {
    }

    public InternalProductcodes(String hscode, String internalProductCode, String hscodeDesc, String commodityCategory, String commodityType, String commodityTechnicalName, String commodityVariety, String commodityForm, Integer priceListIpcMapIdRef, Integer isActiveIpc, Date dateCreated, Date dateDeactivated, Set<PricelistInternalProductcodeDocumentMap> pricelistInternalProductcodeDocumentMaps) {
       this.hscode = hscode;
       this.internalProductCode = internalProductCode;
       this.hscodeDesc = hscodeDesc;
       this.commodityCategory = commodityCategory;
       this.commodityType = commodityType;
       this.commodityTechnicalName = commodityTechnicalName;
       this.commodityVariety = commodityVariety;
       this.commodityForm = commodityForm;
       this.priceListIpcMapIdRef = priceListIpcMapIdRef;
       this.isActiveIpc = isActiveIpc;
       this.dateCreated = dateCreated;
       this.dateDeactivated = dateDeactivated;
       this.pricelistInternalProductcodeDocumentMaps = pricelistInternalProductcodeDocumentMaps;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IPC_ID", unique=true, nullable=false)
    public Integer getIpcId() {
        return this.ipcId;
    }
    
    public void setIpcId(Integer ipcId) {
        this.ipcId = ipcId;
    }

    
    @Column(name="HSCODE", length=45)
    public String getHscode() {
        return this.hscode;
    }
    
    public void setHscode(String hscode) {
        this.hscode = hscode;
    }

    
    @Column(name="Internal_Product_Code")
    public String getInternalProductCode() {
        return this.internalProductCode;
    }
    
    public void setInternalProductCode(String internalProductCode) {
        this.internalProductCode = internalProductCode;
    }

    
    @Column(name="HSCODE_DESC")
    public String getHscodeDesc() {
        return this.hscodeDesc;
    }
    
    public void setHscodeDesc(String hscodeDesc) {
        this.hscodeDesc = hscodeDesc;
    }

    
    @Column(name="Commodity_Category")
    public String getCommodityCategory() {
        return this.commodityCategory;
    }
    
    public void setCommodityCategory(String commodityCategory) {
        this.commodityCategory = commodityCategory;
    }

    
    @Column(name="Commodity_Type")
    public String getCommodityType() {
        return this.commodityType;
    }
    
    public void setCommodityType(String commodityType) {
        this.commodityType = commodityType;
    }

    
    @Column(name="Commodity_Technical_Name")
    public String getCommodityTechnicalName() {
        return this.commodityTechnicalName;
    }
    
    public void setCommodityTechnicalName(String commodityTechnicalName) {
        this.commodityTechnicalName = commodityTechnicalName;
    }

    
    @Column(name="Commodity_Variety")
    public String getCommodityVariety() {
        return this.commodityVariety;
    }
    
    public void setCommodityVariety(String commodityVariety) {
        this.commodityVariety = commodityVariety;
    }

    
    @Column(name="Commodity_Form")
    public String getCommodityForm() {
        return this.commodityForm;
    }
    
    public void setCommodityForm(String commodityForm) {
        this.commodityForm = commodityForm;
    }

    
    @Column(name="Price_List_IPC_MAP_ID_Ref")
    public Integer getPriceListIpcMapIdRef() {
        return this.priceListIpcMapIdRef;
    }
    
    public void setPriceListIpcMapIdRef(Integer priceListIpcMapIdRef) {
        this.priceListIpcMapIdRef = priceListIpcMapIdRef;
    }

    
    @Column(name="isActive_IPC")
    public Integer getIsActiveIpc() {
        return this.isActiveIpc;
    }
    
    public void setIsActiveIpc(Integer isActiveIpc) {
        this.isActiveIpc = isActiveIpc;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Date_Created", length=19)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Date_Deactivated", length=19)
    public Date getDateDeactivated() {
        return this.dateDeactivated;
    }
    
    public void setDateDeactivated(Date dateDeactivated) {
        this.dateDeactivated = dateDeactivated;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="internalProductcodes")
    public Set<PricelistInternalProductcodeDocumentMap> getPricelistInternalProductcodeDocumentMaps() {
        return this.pricelistInternalProductcodeDocumentMaps;
    }
    
    public void setPricelistInternalProductcodeDocumentMaps(Set<PricelistInternalProductcodeDocumentMap> pricelistInternalProductcodeDocumentMaps) {
        this.pricelistInternalProductcodeDocumentMaps = pricelistInternalProductcodeDocumentMaps;
    }




}


