package databaselayer.ecs_kesws.entities;
// Generated Oct 29, 2014 3:56:07 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * KeswsInspectors generated by hbm2java
 */
@Entity
@Table(name="KESWS_INSPECTORS"
    ,catalog="ECS_KESWS"
)
public class KeswsInspectors  implements java.io.Serializable {


     private int keswsInspectorsId;
     private String ecsId;
     private String ecsName;
     private String keswsName;

    public KeswsInspectors() {
    }

	
    public KeswsInspectors(int keswsInspectorsId) {
        this.keswsInspectorsId = keswsInspectorsId;
    }
    public KeswsInspectors(int keswsInspectorsId, String ecsId, String ecsName, String keswsName) {
       this.keswsInspectorsId = keswsInspectorsId;
       this.ecsId = ecsId;
       this.ecsName = ecsName;
       this.keswsName = keswsName;
    }
   
     @Id 

    
    @Column(name="KESWS_INSPECTORS_ID", unique=true, nullable=false)
    public int getKeswsInspectorsId() {
        return this.keswsInspectorsId;
    }
    
    public void setKeswsInspectorsId(int keswsInspectorsId) {
        this.keswsInspectorsId = keswsInspectorsId;
    }

    
    @Column(name="ECS_ID", length=45)
    public String getEcsId() {
        return this.ecsId;
    }
    
    public void setEcsId(String ecsId) {
        this.ecsId = ecsId;
    }

    
    @Column(name="ECS_NAME", length=45)
    public String getEcsName() {
        return this.ecsName;
    }
    
    public void setEcsName(String ecsName) {
        this.ecsName = ecsName;
    }

    
    @Column(name="KESWS_NAME", length=45)
    public String getKeswsName() {
        return this.keswsName;
    }
    
    public void setKeswsName(String keswsName) {
        this.keswsName = keswsName;
    }




}


