package databaselayer.ecs_kesws.entities;
// Generated Oct 29, 2014 3:56:07 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LogTypes generated by hbm2java
 */
@Entity
@Table(name="LOG_TYPES"
    ,catalog="ECS_KESWS"
)
public class LogTypes  implements java.io.Serializable {


     private int logIdLevel;
     private String logLevel;
     private Set<TransactionLogs> transactionLogses = new HashSet<TransactionLogs>(0);

    public LogTypes() {
    }

	
    public LogTypes(int logIdLevel) {
        this.logIdLevel = logIdLevel;
    }
    public LogTypes(int logIdLevel, String logLevel, Set<TransactionLogs> transactionLogses) {
       this.logIdLevel = logIdLevel;
       this.logLevel = logLevel;
       this.transactionLogses = transactionLogses;
    }
   
     @Id 

    
    @Column(name="LOG_ID_LEVEL", unique=true, nullable=false)
    public int getLogIdLevel() {
        return this.logIdLevel;
    }
    
    public void setLogIdLevel(int logIdLevel) {
        this.logIdLevel = logIdLevel;
    }

    
    @Column(name="LOG_LEVEL", length=45)
    public String getLogLevel() {
        return this.logLevel;
    }
    
    public void setLogLevel(String logLevel) {
        this.logLevel = logLevel;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="logTypes")
    public Set<TransactionLogs> getTransactionLogses() {
        return this.transactionLogses;
    }
    
    public void setTransactionLogses(Set<TransactionLogs> transactionLogses) {
        this.transactionLogses = transactionLogses;
    }




}


