package databaselayer.ecs_kesws.entities;
// Generated Oct 29, 2014 3:56:07 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MessageTypes generated by hbm2java
 */
@Entity
@Table(name="MESSAGE_TYPES"
    ,catalog="ECS_KESWS"
)
public class MessageTypes  implements java.io.Serializable {


     private int messageTypeId;
     private String messageName;
     private String messageSource;
     private String messageProcessReq;
     private String messageDest;
     private String messageTypesDesc;
     private Set<ResCdFileMsg> resCdFileMsgs = new HashSet<ResCdFileMsg>(0);
     private Set<RecCdFileMsg> recCdFileMsgs = new HashSet<RecCdFileMsg>(0);

    public MessageTypes() {
    }

	
    public MessageTypes(int messageTypeId) {
        this.messageTypeId = messageTypeId;
    }
    public MessageTypes(int messageTypeId, String messageName, String messageSource, String messageProcessReq, String messageDest, String messageTypesDesc, Set<ResCdFileMsg> resCdFileMsgs, Set<RecCdFileMsg> recCdFileMsgs) {
       this.messageTypeId = messageTypeId;
       this.messageName = messageName;
       this.messageSource = messageSource;
       this.messageProcessReq = messageProcessReq;
       this.messageDest = messageDest;
       this.messageTypesDesc = messageTypesDesc;
       this.resCdFileMsgs = resCdFileMsgs;
       this.recCdFileMsgs = recCdFileMsgs;
    }
   
     @Id 

    
    @Column(name="MESSAGE_TYPE_ID", unique=true, nullable=false)
    public int getMessageTypeId() {
        return this.messageTypeId;
    }
    
    public void setMessageTypeId(int messageTypeId) {
        this.messageTypeId = messageTypeId;
    }

    
    @Column(name="MESSAGE_NAME", length=45)
    public String getMessageName() {
        return this.messageName;
    }
    
    public void setMessageName(String messageName) {
        this.messageName = messageName;
    }

    
    @Column(name="MESSAGE_SOURCE", length=45)
    public String getMessageSource() {
        return this.messageSource;
    }
    
    public void setMessageSource(String messageSource) {
        this.messageSource = messageSource;
    }

    
    @Column(name="MESSAGE_PROCESS_REQ", length=45)
    public String getMessageProcessReq() {
        return this.messageProcessReq;
    }
    
    public void setMessageProcessReq(String messageProcessReq) {
        this.messageProcessReq = messageProcessReq;
    }

    
    @Column(name="MESSAGE_DEST", length=45)
    public String getMessageDest() {
        return this.messageDest;
    }
    
    public void setMessageDest(String messageDest) {
        this.messageDest = messageDest;
    }

    
    @Column(name="MESSAGE_TYPES_DESC", length=45)
    public String getMessageTypesDesc() {
        return this.messageTypesDesc;
    }
    
    public void setMessageTypesDesc(String messageTypesDesc) {
        this.messageTypesDesc = messageTypesDesc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="messageTypes")
    public Set<ResCdFileMsg> getResCdFileMsgs() {
        return this.resCdFileMsgs;
    }
    
    public void setResCdFileMsgs(Set<ResCdFileMsg> resCdFileMsgs) {
        this.resCdFileMsgs = resCdFileMsgs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="messageTypes")
    public Set<RecCdFileMsg> getRecCdFileMsgs() {
        return this.recCdFileMsgs;
    }
    
    public void setRecCdFileMsgs(Set<RecCdFileMsg> recCdFileMsgs) {
        this.recCdFileMsgs = recCdFileMsgs;
    }




}


