package databaselayer.ecs_kesws.entities;
// Generated Oct 29, 2014 3:56:07 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PricelistInternalProductcodeDocumentMap generated by hbm2java
 */
@Entity
@Table(name="PRICELIST_INTERNAL_PRODUCTCODE_DOCUMENT_MAP"
    ,catalog="ECS_KESWS"
)
public class PricelistInternalProductcodeDocumentMap  implements java.io.Serializable {


     private Integer pricelistIpcMapId;
     private EcsDocumentTypes ecsDocumentTypes;
     private InternalProductcodes internalProductcodes;
     private Pricelist pricelist;
     private String documentIdRef;
     private Set<CdFileDetails> cdFileDetailses = new HashSet<CdFileDetails>(0);

    public PricelistInternalProductcodeDocumentMap() {
    }

	
    public PricelistInternalProductcodeDocumentMap(EcsDocumentTypes ecsDocumentTypes, InternalProductcodes internalProductcodes, Pricelist pricelist) {
        this.ecsDocumentTypes = ecsDocumentTypes;
        this.internalProductcodes = internalProductcodes;
        this.pricelist = pricelist;
    }
    public PricelistInternalProductcodeDocumentMap(EcsDocumentTypes ecsDocumentTypes, InternalProductcodes internalProductcodes, Pricelist pricelist, String documentIdRef, Set<CdFileDetails> cdFileDetailses) {
       this.ecsDocumentTypes = ecsDocumentTypes;
       this.internalProductcodes = internalProductcodes;
       this.pricelist = pricelist;
       this.documentIdRef = documentIdRef;
       this.cdFileDetailses = cdFileDetailses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Pricelist_IPC_MAP_ID", unique=true, nullable=false)
    public Integer getPricelistIpcMapId() {
        return this.pricelistIpcMapId;
    }
    
    public void setPricelistIpcMapId(Integer pricelistIpcMapId) {
        this.pricelistIpcMapId = pricelistIpcMapId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DOCUMENT_TYPES_id", nullable=false)
    public EcsDocumentTypes getEcsDocumentTypes() {
        return this.ecsDocumentTypes;
    }
    
    public void setEcsDocumentTypes(EcsDocumentTypes ecsDocumentTypes) {
        this.ecsDocumentTypes = ecsDocumentTypes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="INTERNAL_PRODUCTCODES_IPC_ID_Ref", nullable=false)
    public InternalProductcodes getInternalProductcodes() {
        return this.internalProductcodes;
    }
    
    public void setInternalProductcodes(InternalProductcodes internalProductcodes) {
        this.internalProductcodes = internalProductcodes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PRICELIST_Price_ID_Ref", nullable=false)
    public Pricelist getPricelist() {
        return this.pricelist;
    }
    
    public void setPricelist(Pricelist pricelist) {
        this.pricelist = pricelist;
    }

    
    @Column(name="Document_ID_Ref", length=45)
    public String getDocumentIdRef() {
        return this.documentIdRef;
    }
    
    public void setDocumentIdRef(String documentIdRef) {
        this.documentIdRef = documentIdRef;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pricelistInternalProductcodeDocumentMap")
    public Set<CdFileDetails> getCdFileDetailses() {
        return this.cdFileDetailses;
    }
    
    public void setCdFileDetailses(Set<CdFileDetails> cdFileDetailses) {
        this.cdFileDetailses = cdFileDetailses;
    }




}


