package databaselayer.ecs_kesws.entities;
// Generated Oct 29, 2014 3:56:07 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pricelist generated by hbm2java
 */
@Entity
@Table(name="PRICELIST"
    ,catalog="ECS_KESWS"
)
public class Pricelist  implements java.io.Serializable {


     private Integer priceId;
     private String priceCode;
     private double chargeKshs;
     private String chargeDescription;
     private Integer noOfEntries;
     private Double minWeight;
     private Double maxWeight;
     private Integer isActive;
     private Date dateCreated;
     private Date dateDeactivated;
     private Set<PricelistInternalProductcodeDocumentMap> pricelistInternalProductcodeDocumentMaps = new HashSet<PricelistInternalProductcodeDocumentMap>(0);

    public Pricelist() {
    }

	
    public Pricelist(String priceCode, double chargeKshs, String chargeDescription, Date dateCreated) {
        this.priceCode = priceCode;
        this.chargeKshs = chargeKshs;
        this.chargeDescription = chargeDescription;
        this.dateCreated = dateCreated;
    }
    public Pricelist(String priceCode, double chargeKshs, String chargeDescription, Integer noOfEntries, Double minWeight, Double maxWeight, Integer isActive, Date dateCreated, Date dateDeactivated, Set<PricelistInternalProductcodeDocumentMap> pricelistInternalProductcodeDocumentMaps) {
       this.priceCode = priceCode;
       this.chargeKshs = chargeKshs;
       this.chargeDescription = chargeDescription;
       this.noOfEntries = noOfEntries;
       this.minWeight = minWeight;
       this.maxWeight = maxWeight;
       this.isActive = isActive;
       this.dateCreated = dateCreated;
       this.dateDeactivated = dateDeactivated;
       this.pricelistInternalProductcodeDocumentMaps = pricelistInternalProductcodeDocumentMaps;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Price_ID", unique=true, nullable=false)
    public Integer getPriceId() {
        return this.priceId;
    }
    
    public void setPriceId(Integer priceId) {
        this.priceId = priceId;
    }

    
    @Column(name="Price_Code", nullable=false, length=100)
    public String getPriceCode() {
        return this.priceCode;
    }
    
    public void setPriceCode(String priceCode) {
        this.priceCode = priceCode;
    }

    
    @Column(name="Charge_Kshs", nullable=false, precision=22, scale=0)
    public double getChargeKshs() {
        return this.chargeKshs;
    }
    
    public void setChargeKshs(double chargeKshs) {
        this.chargeKshs = chargeKshs;
    }

    
    @Column(name="Charge_Description", nullable=false, length=65535)
    public String getChargeDescription() {
        return this.chargeDescription;
    }
    
    public void setChargeDescription(String chargeDescription) {
        this.chargeDescription = chargeDescription;
    }

    
    @Column(name="No_Of_Entries")
    public Integer getNoOfEntries() {
        return this.noOfEntries;
    }
    
    public void setNoOfEntries(Integer noOfEntries) {
        this.noOfEntries = noOfEntries;
    }

    
    @Column(name="Min_Weight", precision=22, scale=0)
    public Double getMinWeight() {
        return this.minWeight;
    }
    
    public void setMinWeight(Double minWeight) {
        this.minWeight = minWeight;
    }

    
    @Column(name="Max_Weight", precision=22, scale=0)
    public Double getMaxWeight() {
        return this.maxWeight;
    }
    
    public void setMaxWeight(Double maxWeight) {
        this.maxWeight = maxWeight;
    }

    
    @Column(name="IsActive")
    public Integer getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Integer isActive) {
        this.isActive = isActive;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Date_Created", nullable=false, length=19)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Date_Deactivated", length=19)
    public Date getDateDeactivated() {
        return this.dateDeactivated;
    }
    
    public void setDateDeactivated(Date dateDeactivated) {
        this.dateDeactivated = dateDeactivated;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pricelist")
    public Set<PricelistInternalProductcodeDocumentMap> getPricelistInternalProductcodeDocumentMaps() {
        return this.pricelistInternalProductcodeDocumentMaps;
    }
    
    public void setPricelistInternalProductcodeDocumentMaps(Set<PricelistInternalProductcodeDocumentMap> pricelistInternalProductcodeDocumentMaps) {
        this.pricelistInternalProductcodeDocumentMaps = pricelistInternalProductcodeDocumentMaps;
    }




}


