package databaselayer.ecs_kesws.entities;
// Generated Oct 29, 2014 3:56:07 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * RecCdFileMsg generated by hbm2java
 */
@Entity
@Table(name="REC_CD_FILE_MSG"
    ,catalog="ECS_KESWS"
    , uniqueConstraints = {@UniqueConstraint(columnNames="ECS_CONSIGNEMENT_ID_Ref"), @UniqueConstraint(columnNames="File_Name")} 
)
public class RecCdFileMsg  implements java.io.Serializable {


     private Integer recCdFileId;
     private MessageTypes messageTypes;
     private String fileName;
     private Date receivedDateTime;
     private int isFileXmlValid;
     private String invoiceNo;
     private Date dateTimeSubmittedToEcs;
     private Date dateTimePlanned;
     private Date dateTimeInspected;
     private Date dateTimeCertIssued;
     private String inspectionStatus;
     private int ecsConsignementIdRef;
     private String filePath;
     private Integer ispaymentreq;
     private Set<ResPaymentMsg> resPaymentMsgs = new HashSet<ResPaymentMsg>(0);
     private Set<CdFileDetails> cdFileDetailses = new HashSet<CdFileDetails>(0);
     private Set<TransactionLogs> transactionLogses = new HashSet<TransactionLogs>(0);
     private Set<ResCdFileMsg> resCdFileMsgs = new HashSet<ResCdFileMsg>(0);

    public RecCdFileMsg() {
    }
  public RecCdFileMsg(MessageTypes messageTypes, String fileName, Date receivedDateTime, int isFileXmlValid) {
        this.messageTypes = messageTypes;
        this.fileName = fileName;
        this.receivedDateTime = receivedDateTime;
        this.isFileXmlValid = isFileXmlValid; 
    }
    public RecCdFileMsg(MessageTypes messageTypes, String fileName, Date receivedDateTime, int isFileXmlValid, int ecsConsignementIdRef) {
        this.messageTypes = messageTypes;
        this.fileName = fileName;
        this.receivedDateTime = receivedDateTime;
        this.isFileXmlValid = isFileXmlValid;
        this.ecsConsignementIdRef = ecsConsignementIdRef;
    }
    public RecCdFileMsg(MessageTypes messageTypes, String fileName, Date receivedDateTime, int isFileXmlValid, String invoiceNo, Date dateTimeSubmittedToEcs, Date dateTimePlanned, Date dateTimeInspected, Date dateTimeCertIssued, String inspectionStatus, int ecsConsignementIdRef, String filePath, Integer ispaymentreq, Set<ResPaymentMsg> resPaymentMsgs, Set<CdFileDetails> cdFileDetailses, Set<TransactionLogs> transactionLogses, Set<ResCdFileMsg> resCdFileMsgs) {
       this.messageTypes = messageTypes;
       this.fileName = fileName;
       this.receivedDateTime = receivedDateTime;
       this.isFileXmlValid = isFileXmlValid;
       this.invoiceNo = invoiceNo;
       this.dateTimeSubmittedToEcs = dateTimeSubmittedToEcs;
       this.dateTimePlanned = dateTimePlanned;
       this.dateTimeInspected = dateTimeInspected;
       this.dateTimeCertIssued = dateTimeCertIssued;
       this.inspectionStatus = inspectionStatus;
       this.ecsConsignementIdRef = ecsConsignementIdRef;
       this.filePath = filePath;
       this.ispaymentreq = ispaymentreq;
       this.resPaymentMsgs = resPaymentMsgs;
       this.cdFileDetailses = cdFileDetailses;
       this.transactionLogses = transactionLogses;
       this.resCdFileMsgs = resCdFileMsgs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="REC_CD_File_ID", unique=true, nullable=false)
    public Integer getRecCdFileId() {
        return this.recCdFileId;
    }
    
    public void setRecCdFileId(Integer recCdFileId) {
        this.recCdFileId = recCdFileId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MESSAGE_TYPES_MESSAGE_TYPE_ID", nullable=false)
    public MessageTypes getMessageTypes() {
        return this.messageTypes;
    }
    
    public void setMessageTypes(MessageTypes messageTypes) {
        this.messageTypes = messageTypes;
    }

    
    @Column(name="File_Name", unique=true, nullable=false)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Received_Date_Time", nullable=false, length=19)
    public Date getReceivedDateTime() {
        return this.receivedDateTime;
    }
    
    public void setReceivedDateTime(Date receivedDateTime) {
        this.receivedDateTime = receivedDateTime;
    }

    
    @Column(name="isFile_XML_Valid", nullable=false)
    public int getIsFileXmlValid() {
        return this.isFileXmlValid;
    }
    
    public void setIsFileXmlValid(int isFileXmlValid) {
        this.isFileXmlValid = isFileXmlValid;
    }

    
    @Column(name="Invoice_NO")
    public String getInvoiceNo() {
        return this.invoiceNo;
    }
    
    public void setInvoiceNo(String invoiceNo) {
        this.invoiceNo = invoiceNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Date_Time_Submitted_To_ECS", length=19)
    public Date getDateTimeSubmittedToEcs() {
        return this.dateTimeSubmittedToEcs;
    }
    
    public void setDateTimeSubmittedToEcs(Date dateTimeSubmittedToEcs) {
        this.dateTimeSubmittedToEcs = dateTimeSubmittedToEcs;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Date_Time_Planned", length=19)
    public Date getDateTimePlanned() {
        return this.dateTimePlanned;
    }
    
    public void setDateTimePlanned(Date dateTimePlanned) {
        this.dateTimePlanned = dateTimePlanned;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Date_Time_Inspected", length=19)
    public Date getDateTimeInspected() {
        return this.dateTimeInspected;
    }
    
    public void setDateTimeInspected(Date dateTimeInspected) {
        this.dateTimeInspected = dateTimeInspected;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Date_Time_Cert_Issued", length=19)
    public Date getDateTimeCertIssued() {
        return this.dateTimeCertIssued;
    }
    
    public void setDateTimeCertIssued(Date dateTimeCertIssued) {
        this.dateTimeCertIssued = dateTimeCertIssued;
    }

    
    @Column(name="InspectionStatus", length=50)
    public String getInspectionStatus() {
        return this.inspectionStatus;
    }
    
    public void setInspectionStatus(String inspectionStatus) {
        this.inspectionStatus = inspectionStatus;
    }

    
    @Column(name="ECS_CONSIGNEMENT_ID_Ref", unique=true, nullable=false)
    public int getEcsConsignementIdRef() {
        return this.ecsConsignementIdRef;
    }
    
    public void setEcsConsignementIdRef(int ecsConsignementIdRef) {
        this.ecsConsignementIdRef = ecsConsignementIdRef;
    }

    
    @Column(name="FILE_PATH", length=500)
    public String getFilePath() {
        return this.filePath;
    }
    
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    
    @Column(name="ISPAYMENTREQ")
    public Integer getIspaymentreq() {
        return this.ispaymentreq;
    }
    
    public void setIspaymentreq(Integer ispaymentreq) {
        this.ispaymentreq = ispaymentreq;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="recCdFileMsg")
    public Set<ResPaymentMsg> getResPaymentMsgs() {
        return this.resPaymentMsgs;
    }
    
    public void setResPaymentMsgs(Set<ResPaymentMsg> resPaymentMsgs) {
        this.resPaymentMsgs = resPaymentMsgs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="recCdFileMsg")
    public Set<CdFileDetails> getCdFileDetailses() {
        return this.cdFileDetailses;
    }
    
    public void setCdFileDetailses(Set<CdFileDetails> cdFileDetailses) {
        this.cdFileDetailses = cdFileDetailses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="recCdFileMsg")
    public Set<TransactionLogs> getTransactionLogses() {
        return this.transactionLogses;
    }
    
    public void setTransactionLogses(Set<TransactionLogs> transactionLogses) {
        this.transactionLogses = transactionLogses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="recCdFileMsg")
    public Set<ResCdFileMsg> getResCdFileMsgs() {
        return this.resCdFileMsgs;
    }
    
    public void setResCdFileMsgs(Set<ResCdFileMsg> resCdFileMsgs) {
        this.resCdFileMsgs = resCdFileMsgs;
    }




}


