package databaselayer.ecs_kesws.entities;
// Generated Oct 29, 2014 3:56:07 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RecErrorMsg generated by hbm2java
 */
@Entity
@Table(name="REC_ERROR_MSG"
    ,catalog="ECS_KESWS"
)
public class RecErrorMsg  implements java.io.Serializable {


     private int recErrorMsgId;
     private EcsResCdFileMsg ecsResCdFileMsg;
     private ResCdFileMsg resCdFileMsg;
     private ResPaymentMsg resPaymentMsg;
     private String recErrorMsgTime;
     private String filePath;

    public RecErrorMsg() {
    }

	
    public RecErrorMsg(int recErrorMsgId, EcsResCdFileMsg ecsResCdFileMsg, ResCdFileMsg resCdFileMsg, ResPaymentMsg resPaymentMsg) {
        this.recErrorMsgId = recErrorMsgId;
        this.ecsResCdFileMsg = ecsResCdFileMsg;
        this.resCdFileMsg = resCdFileMsg;
        this.resPaymentMsg = resPaymentMsg;
    }
    public RecErrorMsg(int recErrorMsgId, EcsResCdFileMsg ecsResCdFileMsg, ResCdFileMsg resCdFileMsg, ResPaymentMsg resPaymentMsg, String recErrorMsgTime, String filePath) {
       this.recErrorMsgId = recErrorMsgId;
       this.ecsResCdFileMsg = ecsResCdFileMsg;
       this.resCdFileMsg = resCdFileMsg;
       this.resPaymentMsg = resPaymentMsg;
       this.recErrorMsgTime = recErrorMsgTime;
       this.filePath = filePath;
    }
   
     @Id 

    
    @Column(name="REC_ERROR_MSG_ID", unique=true, nullable=false)
    public int getRecErrorMsgId() {
        return this.recErrorMsgId;
    }
    
    public void setRecErrorMsgId(int recErrorMsgId) {
        this.recErrorMsgId = recErrorMsgId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ECS_RES_CD_FILE_MSG_ECS_RES_CD_FILE_MSG_ID", nullable=false)
    public EcsResCdFileMsg getEcsResCdFileMsg() {
        return this.ecsResCdFileMsg;
    }
    
    public void setEcsResCdFileMsg(EcsResCdFileMsg ecsResCdFileMsg) {
        this.ecsResCdFileMsg = ecsResCdFileMsg;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RES_CD_FILE_MSG_RES_CD_FILE_ID", nullable=false)
    public ResCdFileMsg getResCdFileMsg() {
        return this.resCdFileMsg;
    }
    
    public void setResCdFileMsg(ResCdFileMsg resCdFileMsg) {
        this.resCdFileMsg = resCdFileMsg;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RES_PAYMENT_MSG_PAYEMENT_MSG_ID", nullable=false)
    public ResPaymentMsg getResPaymentMsg() {
        return this.resPaymentMsg;
    }
    
    public void setResPaymentMsg(ResPaymentMsg resPaymentMsg) {
        this.resPaymentMsg = resPaymentMsg;
    }

    
    @Column(name="REC_ERROR_MSG_TIME", length=45)
    public String getRecErrorMsgTime() {
        return this.recErrorMsgTime;
    }
    
    public void setRecErrorMsgTime(String recErrorMsgTime) {
        this.recErrorMsgTime = recErrorMsgTime;
    }

    
    @Column(name="FILE_PATH", length=45)
    public String getFilePath() {
        return this.filePath;
    }
    
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }




}


