package databaselayer.ecs_kesws.entities;
// Generated Oct 29, 2014 3:56:07 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RecPaymentMsg generated by hbm2java
 */
@Entity
@Table(name="REC_PAYMENT_MSG"
    ,catalog="ECS_KESWS"
)
public class RecPaymentMsg  implements java.io.Serializable {


     private Integer receivedPaymentMsgId;
     private ResPaymentMsg resPaymentMsg;
     private Date timeReceived;
     private String amountPaid;
     private String datePaid;
     private String modeOfPayment;
     private String prepaymentAccount;
     private String transactionNumber;
     private String filePath;
     private Set<TransactionLogs> transactionLogses = new HashSet<TransactionLogs>(0);

    public RecPaymentMsg() {
    }

	
    public RecPaymentMsg(ResPaymentMsg resPaymentMsg, Date timeReceived) {
        this.resPaymentMsg = resPaymentMsg;
        this.timeReceived = timeReceived;
    }
    public RecPaymentMsg(ResPaymentMsg resPaymentMsg, Date timeReceived, String amountPaid, String datePaid, String modeOfPayment, String prepaymentAccount, String transactionNumber, String filePath, Set<TransactionLogs> transactionLogses) {
       this.resPaymentMsg = resPaymentMsg;
       this.timeReceived = timeReceived;
       this.amountPaid = amountPaid;
       this.datePaid = datePaid;
       this.modeOfPayment = modeOfPayment;
       this.prepaymentAccount = prepaymentAccount;
       this.transactionNumber = transactionNumber;
       this.filePath = filePath;
       this.transactionLogses = transactionLogses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="RECEIVED_PAYMENT_MSG_ID", unique=true, nullable=false)
    public Integer getReceivedPaymentMsgId() {
        return this.receivedPaymentMsgId;
    }
    
    public void setReceivedPaymentMsgId(Integer receivedPaymentMsgId) {
        this.receivedPaymentMsgId = receivedPaymentMsgId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SENT_PAYEMENT_MSG_PAYEMENT_MSG_ID", nullable=false)
    public ResPaymentMsg getResPaymentMsg() {
        return this.resPaymentMsg;
    }
    
    public void setResPaymentMsg(ResPaymentMsg resPaymentMsg) {
        this.resPaymentMsg = resPaymentMsg;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TIME_RECEIVED", nullable=false, length=19)
    public Date getTimeReceived() {
        return this.timeReceived;
    }
    
    public void setTimeReceived(Date timeReceived) {
        this.timeReceived = timeReceived;
    }

    
    @Column(name="AMOUNT_PAID", length=45)
    public String getAmountPaid() {
        return this.amountPaid;
    }
    
    public void setAmountPaid(String amountPaid) {
        this.amountPaid = amountPaid;
    }

    
    @Column(name="DATE_PAID")
    public String getDatePaid() {
        return this.datePaid;
    }
    
    public void setDatePaid(String datePaid) {
        this.datePaid = datePaid;
    }

    
    @Column(name="MODE_OF_PAYMENT")
    public String getModeOfPayment() {
        return this.modeOfPayment;
    }
    
    public void setModeOfPayment(String modeOfPayment) {
        this.modeOfPayment = modeOfPayment;
    }

    
    @Column(name="PREPAYMENT_ACCOUNT", length=45)
    public String getPrepaymentAccount() {
        return this.prepaymentAccount;
    }
    
    public void setPrepaymentAccount(String prepaymentAccount) {
        this.prepaymentAccount = prepaymentAccount;
    }

    
    @Column(name="TRANSACTION_NUMBER", length=45)
    public String getTransactionNumber() {
        return this.transactionNumber;
    }
    
    public void setTransactionNumber(String transactionNumber) {
        this.transactionNumber = transactionNumber;
    }

    
    @Column(name="FILE_PATH", length=45)
    public String getFilePath() {
        return this.filePath;
    }
    
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="recPaymentMsg")
    public Set<TransactionLogs> getTransactionLogses() {
        return this.transactionLogses;
    }
    
    public void setTransactionLogses(Set<TransactionLogs> transactionLogses) {
        this.transactionLogses = transactionLogses;
    }




}


