package databaselayer.ecs_kesws.entities;
// Generated Oct 29, 2014 3:56:07 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ResCdFileMsg generated by hbm2java
 */
@Entity
@Table(name="RES_CD_FILE_MSG"
    ,catalog="ECS_KESWS"
)
public class ResCdFileMsg  implements java.io.Serializable {


     private Integer resCdFileId;
     private MessageTypes messageTypes;
     private RecCdFileMsg recCdFileMsg;
     private String messageType;
     private String outboxFileItemTotalWeight;
     private String outboxFileItemTotalCost;
     private String outboxFileItemDetails;
     private String outboxFileItemDetailInspectionType;
     private String outboxFileItemInspectorId;
     private String comments;
     private String filePath;
     private Date timeSent;
     private Integer sendAck;
     private Set<RecErrorMsg> recErrorMsgs = new HashSet<RecErrorMsg>(0);
     private Set<TransactionLogs> transactionLogses = new HashSet<TransactionLogs>(0);

    public ResCdFileMsg() {
    }

	
    public ResCdFileMsg(MessageTypes messageTypes, RecCdFileMsg recCdFileMsg) {
        this.messageTypes = messageTypes;
        this.recCdFileMsg = recCdFileMsg;
    }
    public ResCdFileMsg(MessageTypes messageTypes, RecCdFileMsg recCdFileMsg, String messageType, String outboxFileItemTotalWeight, String outboxFileItemTotalCost, String outboxFileItemDetails, String outboxFileItemDetailInspectionType, String outboxFileItemInspectorId, String comments, String filePath, Date timeSent, Integer sendAck, Set<RecErrorMsg> recErrorMsgs, Set<TransactionLogs> transactionLogses) {
       this.messageTypes = messageTypes;
       this.recCdFileMsg = recCdFileMsg;
       this.messageType = messageType;
       this.outboxFileItemTotalWeight = outboxFileItemTotalWeight;
       this.outboxFileItemTotalCost = outboxFileItemTotalCost;
       this.outboxFileItemDetails = outboxFileItemDetails;
       this.outboxFileItemDetailInspectionType = outboxFileItemDetailInspectionType;
       this.outboxFileItemInspectorId = outboxFileItemInspectorId;
       this.comments = comments;
       this.filePath = filePath;
       this.timeSent = timeSent;
       this.sendAck = sendAck;
       this.recErrorMsgs = recErrorMsgs;
       this.transactionLogses = transactionLogses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="RES_CD_FILE_ID", unique=true, nullable=false)
    public Integer getResCdFileId() {
        return this.resCdFileId;
    }
    
    public void setResCdFileId(Integer resCdFileId) {
        this.resCdFileId = resCdFileId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MESSAGE_TYPES_MESSAGE_TYPE_ID", nullable=false)
    public MessageTypes getMessageTypes() {
        return this.messageTypes;
    }
    
    public void setMessageTypes(MessageTypes messageTypes) {
        this.messageTypes = messageTypes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="REC_CD_FILE_MSG_REC_CD_FILE_ID", nullable=false)
    public RecCdFileMsg getRecCdFileMsg() {
        return this.recCdFileMsg;
    }
    
    public void setRecCdFileMsg(RecCdFileMsg recCdFileMsg) {
        this.recCdFileMsg = recCdFileMsg;
    }

    
    @Column(name="MESSAGE_TYPE", length=45)
    public String getMessageType() {
        return this.messageType;
    }
    
    public void setMessageType(String messageType) {
        this.messageType = messageType;
    }

    
    @Column(name="OUTBOX_FILE_ITEM_TOTAL_WEIGHT", length=45)
    public String getOutboxFileItemTotalWeight() {
        return this.outboxFileItemTotalWeight;
    }
    
    public void setOutboxFileItemTotalWeight(String outboxFileItemTotalWeight) {
        this.outboxFileItemTotalWeight = outboxFileItemTotalWeight;
    }

    
    @Column(name="OUTBOX_FILE_ITEM_TOTAL_COST", length=45)
    public String getOutboxFileItemTotalCost() {
        return this.outboxFileItemTotalCost;
    }
    
    public void setOutboxFileItemTotalCost(String outboxFileItemTotalCost) {
        this.outboxFileItemTotalCost = outboxFileItemTotalCost;
    }

    
    @Column(name="OUTBOX_FILE_ITEM_DETAILS", length=1000)
    public String getOutboxFileItemDetails() {
        return this.outboxFileItemDetails;
    }
    
    public void setOutboxFileItemDetails(String outboxFileItemDetails) {
        this.outboxFileItemDetails = outboxFileItemDetails;
    }

    
    @Column(name="OUTBOX_FILE_ITEM_DETAIL_INSPECTION_TYPE", length=45)
    public String getOutboxFileItemDetailInspectionType() {
        return this.outboxFileItemDetailInspectionType;
    }
    
    public void setOutboxFileItemDetailInspectionType(String outboxFileItemDetailInspectionType) {
        this.outboxFileItemDetailInspectionType = outboxFileItemDetailInspectionType;
    }

    
    @Column(name="OUTBOX_FILE_ITEM_INSPECTOR_ID", length=45)
    public String getOutboxFileItemInspectorId() {
        return this.outboxFileItemInspectorId;
    }
    
    public void setOutboxFileItemInspectorId(String outboxFileItemInspectorId) {
        this.outboxFileItemInspectorId = outboxFileItemInspectorId;
    }

    
    @Column(name="COMMENTS")
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }

    
    @Column(name="FILE_PATH")
    public String getFilePath() {
        return this.filePath;
    }
    
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TIME_SENT", length=19)
    public Date getTimeSent() {
        return this.timeSent;
    }
    
    public void setTimeSent(Date timeSent) {
        this.timeSent = timeSent;
    }

    
    @Column(name="SEND_ACK")
    public Integer getSendAck() {
        return this.sendAck;
    }
    
    public void setSendAck(Integer sendAck) {
        this.sendAck = sendAck;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="resCdFileMsg")
    public Set<RecErrorMsg> getRecErrorMsgs() {
        return this.recErrorMsgs;
    }
    
    public void setRecErrorMsgs(Set<RecErrorMsg> recErrorMsgs) {
        this.recErrorMsgs = recErrorMsgs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="resCdFileMsg")
    public Set<TransactionLogs> getTransactionLogses() {
        return this.transactionLogses;
    }
    
    public void setTransactionLogses(Set<TransactionLogs> transactionLogses) {
        this.transactionLogses = transactionLogses;
    }




}


