package databaselayer.ecs_kesws.entities;
// Generated Oct 29, 2014 3:56:07 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ResPaymentMsg generated by hbm2java
 */
@Entity
@Table(name="RES_PAYMENT_MSG"
    ,catalog="ECS_KESWS"
)
public class ResPaymentMsg  implements java.io.Serializable {


     private Integer payementMsgId;
     private RecCdFileMsg recCdFileMsg;
     private Date timeSent;
     private String amount;
     private String currency;
     private String revenueCode;
     private String filePath;
     private Integer sentAck;
     private Set<TransactionLogs> transactionLogses = new HashSet<TransactionLogs>(0);
     private Set<RecPaymentMsg> recPaymentMsgs = new HashSet<RecPaymentMsg>(0);
     private Set<RecErrorMsg> recErrorMsgs = new HashSet<RecErrorMsg>(0);

    public ResPaymentMsg() {
    }

	
    public ResPaymentMsg(RecCdFileMsg recCdFileMsg) {
        this.recCdFileMsg = recCdFileMsg;
    }
    public ResPaymentMsg(RecCdFileMsg recCdFileMsg, Date timeSent, String amount, String currency, String revenueCode, String filePath, Integer sentAck, Set<TransactionLogs> transactionLogses, Set<RecPaymentMsg> recPaymentMsgs, Set<RecErrorMsg> recErrorMsgs) {
       this.recCdFileMsg = recCdFileMsg;
       this.timeSent = timeSent;
       this.amount = amount;
       this.currency = currency;
       this.revenueCode = revenueCode;
       this.filePath = filePath;
       this.sentAck = sentAck;
       this.transactionLogses = transactionLogses;
       this.recPaymentMsgs = recPaymentMsgs;
       this.recErrorMsgs = recErrorMsgs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PAYEMENT_MSG_ID", unique=true, nullable=false)
    public Integer getPayementMsgId() {
        return this.payementMsgId;
    }
    
    public void setPayementMsgId(Integer payementMsgId) {
        this.payementMsgId = payementMsgId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="INBOX_MSG_Inbox_ID", nullable=false)
    public RecCdFileMsg getRecCdFileMsg() {
        return this.recCdFileMsg;
    }
    
    public void setRecCdFileMsg(RecCdFileMsg recCdFileMsg) {
        this.recCdFileMsg = recCdFileMsg;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TIME_SENT", length=19)
    public Date getTimeSent() {
        return this.timeSent;
    }
    
    public void setTimeSent(Date timeSent) {
        this.timeSent = timeSent;
    }

    
    @Column(name="AMOUNT", length=50)
    public String getAmount() {
        return this.amount;
    }
    
    public void setAmount(String amount) {
        this.amount = amount;
    }

    
    @Column(name="CURRENCY", length=50)
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    
    @Column(name="REVENUE_CODE", length=50)
    public String getRevenueCode() {
        return this.revenueCode;
    }
    
    public void setRevenueCode(String revenueCode) {
        this.revenueCode = revenueCode;
    }

    
    @Column(name="FILE_PATH")
    public String getFilePath() {
        return this.filePath;
    }
    
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    
    @Column(name="SENT_ACK")
    public Integer getSentAck() {
        return this.sentAck;
    }
    
    public void setSentAck(Integer sentAck) {
        this.sentAck = sentAck;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="resPaymentMsg")
    public Set<TransactionLogs> getTransactionLogses() {
        return this.transactionLogses;
    }
    
    public void setTransactionLogses(Set<TransactionLogs> transactionLogses) {
        this.transactionLogses = transactionLogses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="resPaymentMsg")
    public Set<RecPaymentMsg> getRecPaymentMsgs() {
        return this.recPaymentMsgs;
    }
    
    public void setRecPaymentMsgs(Set<RecPaymentMsg> recPaymentMsgs) {
        this.recPaymentMsgs = recPaymentMsgs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="resPaymentMsg")
    public Set<RecErrorMsg> getRecErrorMsgs() {
        return this.recErrorMsgs;
    }
    
    public void setRecErrorMsgs(Set<RecErrorMsg> recErrorMsgs) {
        this.recErrorMsgs = recErrorMsgs;
    }




}


