package databaselayer.ecs_kesws.entities;
// Generated Oct 29, 2014 3:56:07 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TransactionLogs generated by hbm2java
 */
@Entity
@Table(name="TRANSACTION_LOGS"
    ,catalog="ECS_KESWS"
)
public class TransactionLogs  implements java.io.Serializable {


     private Integer logId;
     private LogTypes logTypes;
     private RecCdFileMsg recCdFileMsg;
     private RecPaymentMsg recPaymentMsg;
     private ResCdFileMsg resCdFileMsg;
     private ResPaymentMsg resPaymentMsg;
     private String logDetails;
     private Date dateTimeLogged;

    public TransactionLogs() {
    }

	
    public TransactionLogs(LogTypes logTypes, ResCdFileMsg resCdFileMsg, String logDetails, Date dateTimeLogged) {
        this.logTypes = logTypes;
        this.resCdFileMsg = resCdFileMsg;
        this.logDetails = logDetails;
        this.dateTimeLogged = dateTimeLogged;
    }
    public TransactionLogs(LogTypes logTypes, RecCdFileMsg recCdFileMsg, RecPaymentMsg recPaymentMsg, ResCdFileMsg resCdFileMsg, ResPaymentMsg resPaymentMsg, String logDetails, Date dateTimeLogged) {
       this.logTypes = logTypes;
       this.recCdFileMsg = recCdFileMsg;
       this.recPaymentMsg = recPaymentMsg;
       this.resCdFileMsg = resCdFileMsg;
       this.resPaymentMsg = resPaymentMsg;
       this.logDetails = logDetails;
       this.dateTimeLogged = dateTimeLogged;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Log_ID", unique=true, nullable=false)
    public Integer getLogId() {
        return this.logId;
    }
    
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="LOG_TYPES_LOG_ID_LEVEL", nullable=false)
    public LogTypes getLogTypes() {
        return this.logTypes;
    }
    
    public void setLogTypes(LogTypes logTypes) {
        this.logTypes = logTypes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="REC_CD_FILE_MSG_REC_CD_FILE_ID")
    public RecCdFileMsg getRecCdFileMsg() {
        return this.recCdFileMsg;
    }
    
    public void setRecCdFileMsg(RecCdFileMsg recCdFileMsg) {
        this.recCdFileMsg = recCdFileMsg;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="REC_PAYMENT_MSG_RECEIVED_PAYMENT_MSG_ID")
    public RecPaymentMsg getRecPaymentMsg() {
        return this.recPaymentMsg;
    }
    
    public void setRecPaymentMsg(RecPaymentMsg recPaymentMsg) {
        this.recPaymentMsg = recPaymentMsg;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RES_CD_FILE_MSG_RES_CD_FILE_ID", nullable=false)
    public ResCdFileMsg getResCdFileMsg() {
        return this.resCdFileMsg;
    }
    
    public void setResCdFileMsg(ResCdFileMsg resCdFileMsg) {
        this.resCdFileMsg = resCdFileMsg;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RES_PAYMENT_MSG_PAYEMENT_MSG_ID")
    public ResPaymentMsg getResPaymentMsg() {
        return this.resPaymentMsg;
    }
    
    public void setResPaymentMsg(ResPaymentMsg resPaymentMsg) {
        this.resPaymentMsg = resPaymentMsg;
    }

    
    @Column(name="Log_Details", nullable=false, length=65535)
    public String getLogDetails() {
        return this.logDetails;
    }
    
    public void setLogDetails(String logDetails) {
        this.logDetails = logDetails;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Date_Time_Logged", nullable=false, length=19)
    public Date getDateTimeLogged() {
        return this.dateTimeLogged;
    }
    
    public void setDateTimeLogged(Date dateTimeLogged) {
        this.dateTimeLogged = dateTimeLogged;
    }




}


